spellAbilityTable = {
    -- job abilities
    ["Mighty Strikes"] = {id=16,recastId=0,command="/ja"},
    ["Hundred Fists"] = {id=17,recastId=0,command="/ja"},
    ["Benediction"] = {id=18,recastId=0,command="/ja"},
    ["Manafont"] = {id=19,recastId=0,command="/ja"},
    ["Chainspell"] = {id=20,recastId=0,command="/ja"},
    ["Perfect Dodge"] = {id=21,recastId=0,command="/ja"},
    ["Invincible"] = {id=22,recastId=0,command="/ja"},
    ["Blood Weapon"] = {id=23,recastId=0,command="/ja"},
    ["Familiar"] = {id=24,recastId=0,command="/ja"},
    ["Soul Voice"] = {id=25,recastId=0,command="/ja"},
    ["Eagle Eye Shot"] = {id=26,recastId=0,command="/ja"},
    ["Meikyo Shisui"] = {id=27,recastId=0,command="/ja"},
    ["Mijin Gakure"] = {id=28,recastId=0,command="/ja"},
    ["Spirit Surge"] = {id=29,recastId=0,command="/ja"},
    ["Astral Flow"] = {id=30,recastId=0,command="/ja"},
    ["Berserk"] = {id=31,recastId=1,command="/ja"},
    ["Warcry"] = {id=32,recastId=2,command="/ja"},
    ["Defender"] = {id=33,recastId=3,command="/ja"},
    ["Aggressor"] = {id=34,recastId=4,command="/ja"},
    ["Provoke"] = {id=35,recastId=5,command="/ja"},
    ["Focus"] = {id=36,recastId=13,command="/ja"},
    ["Dodge"] = {id=37,recastId=14,command="/ja"},
    ["Chakra"] = {id=38,recastId=15,command="/ja"},
    ["Boost"] = {id=39,recastId=16,command="/ja"},
    ["Counterstance"] = {id=40,recastId=17,command="/ja"},
    ["Steal"] = {id=41,recastId=60,command="/ja"},
    ["Flee"] = {id=42,recastId=62,command="/ja"},
    ["Hide"] = {id=43,recastId=63,command="/ja"},
    ["Sneak Attack"] = {id=44,recastId=64,command="/ja"},
    ["Mug"] = {id=45,recastId=65,command="/ja"},
    ["Shield Bash"] = {id=46,recastId=73,command="/ja"},
    ["Holy Circle"] = {id=47,recastId=74,command="/ja"},
    ["Sentinel"] = {id=48,recastId=75,command="/ja"},
    ["Souleater"] = {id=49,recastId=85,command="/ja"},
    ["Arcane Circle"] = {id=50,recastId=86,command="/ja"},
    ["Last Resort"] = {id=51,recastId=87,command="/ja"},
    ["Charm"] = {id=52,recastId=97,command="/ja"},
    ["Gauge"] = {id=53,recastId=98,command="/ja"},
    ["Tame"] = {id=54,recastId=99,command="/ja"},
    ["Pet commands"] = {id=55,recastId=255,command="/ja"},
    ["Scavenge"] = {id=56,recastId=121,command="/ja"},
    ["Shadowbind"] = {id=57,recastId=122,command="/ja"},
    ["Camouflage"] = {id=58,recastId=123,command="/ja"},
    ["Sharpshot"] = {id=59,recastId=124,command="/ja"},
    ["Barrage"] = {id=60,recastId=125,command="/ja"},
    ["Call Wyvern"] = {id=61,recastId=163,command="/ja"},
    ["Third Eye"] = {id=62,recastId=133,command="/ja"},
    ["Meditate"] = {id=63,recastId=134,command="/ja"},
    ["Warding Circle"] = {id=64,recastId=135,command="/ja"},
    ["Ancient Circle"] = {id=65,recastId=157,command="/ja"},
    ["Jump"] = {id=66,recastId=158,command="/ja"},
    ["High Jump"] = {id=67,recastId=159,command="/ja"},
    ["Super Jump"] = {id=68,recastId=160,command="/ja"},
    ["Fight"] = {id=69,recastId=100,command="/ja"},
    ["Heel"] = {id=70,recastId=101,command="/ja"},
    ["Leave"] = {id=71,recastId=101,command="/ja"},
    ["Sic"] = {id=72,recastId=102,command="/ja"},
    ["Stay"] = {id=73,recastId=101,command="/ja"},
    ["Divine Seal"] = {id=74,recastId=26,command="/ja"},
    ["Elemental Seal"] = {id=75,recastId=38,command="/ja"},
    ["Trick Attack"] = {id=76,recastId=66,command="/ja"},
    ["Weapon Bash"] = {id=77,recastId=88,command="/ja"},
    ["Reward"] = {id=78,recastId=103,command="/ja"},
    ["Cover"] = {id=79,recastId=76,command="/ja"},
    ["Spirit Link"] = {id=80,recastId=162,command="/ja"},
    ["Enrage"] = {id=81,recastId=6,command="/ja"},
    ["Chi Blast"] = {id=82,recastId=18,command="/ja"},
    ["Convert"] = {id=83,recastId=49,command="/ja"},
    ["Accomplice"] = {id=84,recastId=69,command="/ja"},
    ["Call Beast"] = {id=85,recastId=104,command="/ja"},
    ["Unlimited Shot"] = {id=86,recastId=126,command="/ja"},
    ["Dismiss"] = {id=87,recastId=161,command="/ja"},
    ["Assault"] = {id=88,recastId=170,command="/ja"},
    ["Retreat"] = {id=89,recastId=171,command="/ja"},
    ["Release"] = {id=90,recastId=172,command="/ja"},
    ["Blood Pact: Rage"] = {id=91,recastId=173,command="/ja"},
    ["Rampart"] = {id=92,recastId=77,command="/ja"},
    ["Azure Lore"] = {id=93,recastId=0,command="/ja"},
    ["Chain Affinity"] = {id=94,recastId=181,command="/ja"},
    ["Burst Affinity"] = {id=95,recastId=182,command="/ja"},
    ["Wild Card"] = {id=96,recastId=0,command="/ja"},
    ["Phantom Roll"] = {id=97,recastId=193,command="/ja"},
    ["Fighter's Roll"] = {id=98,recastId=193,command="/ja"},
    ["Monk's Roll"] = {id=99,recastId=193,command="/ja"},
    ["Healer's Roll"] = {id=100,recastId=193,command="/ja"},
    ["Wizard's Roll"] = {id=101,recastId=193,command="/ja"},
    ["Warlock's Roll"] = {id=102,recastId=193,command="/ja"},
    ["Rogue's Roll"] = {id=103,recastId=193,command="/ja"},
    ["Gallant's Roll"] = {id=104,recastId=193,command="/ja"},
    ["Chaos Roll"] = {id=105,recastId=193,command="/ja"},
    ["Beast Roll"] = {id=106,recastId=193,command="/ja"},
    ["Choral Roll"] = {id=107,recastId=193,command="/ja"},
    ["Hunter's Roll"] = {id=108,recastId=193,command="/ja"},
    ["Samurai Roll"] = {id=109,recastId=193,command="/ja"},
    ["Ninja Roll"] = {id=110,recastId=193,command="/ja"},
    ["Drachen Roll"] = {id=111,recastId=193,command="/ja"},
    ["Evoker's Roll"] = {id=112,recastId=193,command="/ja"},
    ["Magus's Roll"] = {id=113,recastId=193,command="/ja"},
    ["Corsair's Roll"] = {id=114,recastId=193,command="/ja"},
    ["Puppet Roll"] = {id=115,recastId=193,command="/ja"},
    ["Dancer's Roll"] = {id=116,recastId=193,command="/ja"},
    ["Scholar's Roll"] = {id=117,recastId=193,command="/ja"},
    ["Bolter's Roll"] = {id=118,recastId=193,command="/ja"},
    ["Caster's Roll"] = {id=119,recastId=193,command="/ja"},
    ["Courser's Roll"] = {id=120,recastId=193,command="/ja"},
    ["Blitzer's Roll"] = {id=121,recastId=193,command="/ja"},
    ["Tactician's Roll"] = {id=122,recastId=193,command="/ja"},
    ["Double-Up"] = {id=123,recastId=194,command="/ja"},
    ["Quick Draw"] = {id=124,recastId=199,command="/ja"},
    ["Fire Shot"] = {id=125,recastId=195,command="/ja"},
    ["Ice Shot"] = {id=126,recastId=195,command="/ja"},
    ["Wind Shot"] = {id=127,recastId=195,command="/ja"},
    ["Earth Shot"] = {id=128,recastId=195,command="/ja"},
    ["Thunder Shot"] = {id=129,recastId=195,command="/ja"},
    ["Water Shot"] = {id=130,recastId=195,command="/ja"},
    ["Light Shot"] = {id=131,recastId=195,command="/ja"},
    ["Dark Shot"] = {id=132,recastId=195,command="/ja"},
    ["Random Deal"] = {id=133,recastId=196,command="/ja"},
    ["Overdrive"] = {id=135,recastId=0,command="/ja"},
    ["Activate"] = {id=136,recastId=205,command="/ja"},
    ["Repair"] = {id=137,recastId=206,command="/ja"},
    ["Deploy"] = {id=138,recastId=207,command="/ja"},
    ["Deactivate"] = {id=139,recastId=208,command="/ja"},
    ["Retrieve"] = {id=140,recastId=209,command="/ja"},
    ["Fire Maneuver"] = {id=141,recastId=210,command="/ja"},
    ["Ice Maneuver"] = {id=142,recastId=210,command="/ja"},
    ["Wind Maneuver"] = {id=143,recastId=210,command="/ja"},
    ["Earth Maneuver"] = {id=144,recastId=210,command="/ja"},
    ["Thunder Maneuver"] = {id=145,recastId=210,command="/ja"},
    ["Water Maneuver"] = {id=146,recastId=210,command="/ja"},
    ["Light Maneuver"] = {id=147,recastId=210,command="/ja"},
    ["Dark Maneuver"] = {id=148,recastId=210,command="/ja"},
    ["Warrior's Charge"] = {id=149,recastId=6,command="/ja"},
    ["Tomahawk"] = {id=150,recastId=7,command="/ja"},
    ["Mantra"] = {id=151,recastId=19,command="/ja"},
    ["Formless Strikes"] = {id=152,recastId=20,command="/ja"},
    ["Martyr"] = {id=153,recastId=27,command="/ja"},
    ["Devotion"] = {id=154,recastId=28,command="/ja"},
    ["Assassin's Charge"] = {id=155,recastId=67,command="/ja"},
    ["Feint"] = {id=156,recastId=68,command="/ja"},
    ["Fealty"] = {id=157,recastId=78,command="/ja"},
    ["Chivalry"] = {id=158,recastId=79,command="/ja"},
    ["Dark Seal"] = {id=159,recastId=89,command="/ja"},
    ["Diabolic Eye"] = {id=160,recastId=90,command="/ja"},
    ["Feral Howl"] = {id=161,recastId=105,command="/ja"},
    ["Killer Instinct"] = {id=162,recastId=106,command="/ja"},
    ["Nightingale"] = {id=163,recastId=109,command="/ja"},
    ["Troubadour"] = {id=164,recastId=110,command="/ja"},
    ["Stealth Shot"] = {id=165,recastId=127,command="/ja"},
    ["Flashy Shot"] = {id=166,recastId=128,command="/ja"},
    ["Shikikoyo"] = {id=167,recastId=136,command="/ja"},
    ["Blade Bash"] = {id=168,recastId=137,command="/ja"},
    ["Deep Breathing"] = {id=169,recastId=164,command="/ja"},
    ["Angon"] = {id=170,recastId=165,command="/ja"},
    ["Sange"] = {id=171,recastId=145,command="/ja"},
    ["Blood Pact: Ward"] = {id=172,recastId=174,command="/ja"},
    ["Hasso"] = {id=173,recastId=138,command="/ja"},
    ["Seigan"] = {id=174,recastId=139,command="/ja"},
    ["Convergence"] = {id=175,recastId=183,command="/ja"},
    ["Diffusion"] = {id=176,recastId=184,command="/ja"},
    ["Snake Eye"] = {id=177,recastId=197,command="/ja"},
    ["Fold"] = {id=178,recastId=198,command="/ja"},
    ["Role Reversal"] = {id=179,recastId=211,command="/ja"},
    ["Ventriloquy"] = {id=180,recastId=212,command="/ja"},
    ["Trance"] = {id=181,recastId=0,command="/ja"},
    ["Sambas"] = {id=182,recastId=216,command="/ja"},
    ["Waltzes"] = {id=183,recastId=227,command="/ja"},
    ["Drain Samba"] = {id=184,recastId=216,command="/ja"},
    ["Drain Samba II"] = {id=185,recastId=216,command="/ja"},
    ["Drain Samba III"] = {id=186,recastId=216,command="/ja"},
    ["Aspir Samba"] = {id=187,recastId=216,command="/ja"},
    ["Aspir Samba II"] = {id=188,recastId=216,command="/ja"},
    ["Haste Samba"] = {id=189,recastId=216,command="/ja"},
    ["Curing Waltz"] = {id=190,recastId=217,command="/ja"},
    ["Curing Waltz II"] = {id=191,recastId=186,command="/ja"},
    ["Curing Waltz III"] = {id=192,recastId=187,command="/ja"},
    ["Curing Waltz IV"] = {id=193,recastId=188,command="/ja"},
    ["Healing Waltz"] = {id=194,recastId=215,command="/ja"},
    ["Divine Waltz"] = {id=195,recastId=225,command="/ja"},
    ["Spectral Jig"] = {id=196,recastId=218,command="/ja"},
    ["Chocobo Jig"] = {id=197,recastId=218,command="/ja"},
    ["Jigs"] = {id=198,recastId=218,command="/ja"},
    ["Steps"] = {id=199,recastId=220,command="/ja"},
    ["Flourishes I"] = {id=200,recastId=221,command="/ja"},
    ["Quickstep"] = {id=201,recastId=220,command="/ja"},
    ["Box Step"] = {id=202,recastId=220,command="/ja"},
    ["Stutter Step"] = {id=203,recastId=220,command="/ja"},
    ["Animated Flourish"] = {id=204,recastId=221,command="/ja"},
    ["Desperate Flourish"] = {id=205,recastId=221,command="/ja"},
    ["Reverse Flourish"] = {id=206,recastId=222,command="/ja"},
    ["Violent Flourish"] = {id=207,recastId=221,command="/ja"},
    ["Building Flourish"] = {id=208,recastId=222,command="/ja"},
    ["Wild Flourish"] = {id=209,recastId=222,command="/ja"},
    ["Tabula Rasa"] = {id=210,recastId=0,command="/ja"},
    ["Light Arts"] = {id=211,recastId=228,command="/ja"},
    ["Dark Arts"] = {id=212,recastId=232,command="/ja"},
    ["Flourishes II"] = {id=213,recastId=222,command="/ja"},
    ["Modus Veritas"] = {id=214,recastId=230,command="/ja"},
    ["Penury"] = {id=215,recastId=231,command="/ja"},
    ["Celerity"] = {id=216,recastId=231,command="/ja"},
    ["Rapture"] = {id=217,recastId=231,command="/ja"},
    ["Accession"] = {id=218,recastId=231,command="/ja"},
    ["Parsimony"] = {id=219,recastId=231,command="/ja"},
    ["Alacrity"] = {id=220,recastId=231,command="/ja"},
    ["Ebullience"] = {id=221,recastId=231,command="/ja"},
    ["Manifestation"] = {id=222,recastId=231,command="/ja"},
    ["Stratagems"] = {id=223,recastId=233,command="/ja"},
    ["Velocity Shot"] = {id=224,recastId=129,command="/ja"},
    ["Snarl"] = {id=225,recastId=107,command="/ja"},
    ["Retaliation"] = {id=226,recastId=8,command="/ja"},
    ["Footwork"] = {id=227,recastId=21,command="/ja"},
    ["Despoil"] = {id=228,recastId=61,command="/ja"},
    ["Pianissimo"] = {id=229,recastId=112,command="/ja"},
    ["Sekkanoki"] = {id=230,recastId=140,command="/ja"},
    ["Elemental Siphon"] = {id=232,recastId=175,command="/ja"},
    ["Sublimation"] = {id=233,recastId=234,command="/ja"},
    ["Addendum: White"] = {id=234,recastId=231,command="/ja"},
    ["Addendum: Black"] = {id=235,recastId=231,command="/ja"},
    ["Collaborator"] = {id=236,recastId=69,command="/ja"},
    ["Saber Dance"] = {id=237,recastId=219,command="/ja"},
    ["Fan Dance"] = {id=238,recastId=224,command="/ja"},
    ["No Foot Rise"] = {id=239,recastId=223,command="/ja"},
    ["Altruism"] = {id=240,recastId=231,command="/ja"},
    ["Focalization"] = {id=241,recastId=231,command="/ja"},
    ["Tranquility"] = {id=242,recastId=231,command="/ja"},
    ["Equanimity"] = {id=243,recastId=231,command="/ja"},
    ["Enlightenment"] = {id=244,recastId=235,command="/ja"},
    ["Afflatus Solace"] = {id=245,recastId=29,command="/ja"},
    ["Afflatus Misery"] = {id=246,recastId=30,command="/ja"},
    ["Composure"] = {id=247,recastId=50,command="/ja"},
    ["Yonin"] = {id=248,recastId=146,command="/ja"},
    ["Innin"] = {id=249,recastId=147,command="/ja"},
    ["Avatar's Favor"] = {id=250,recastId=176,command="/ja"},
    ["Ready"] = {id=251,recastId=255,command="/ja"},
    ["Restraint"] = {id=252,recastId=9,command="/ja"},
    ["Perfect Counter"] = {id=253,recastId=22,command="/ja"},
    ["Mana Wall"] = {id=254,recastId=39,command="/ja"},
    ["Divine Emblem"] = {id=255,recastId=80,command="/ja"},
    ["Nether Void"] = {id=256,recastId=91,command="/ja"},
    ["Double Shot"] = {id=257,recastId=126,command="/ja"},
    ["Sengikori"] = {id=258,recastId=141,command="/ja"},
    ["Futae"] = {id=259,recastId=148,command="/ja"},
    ["Spirit Jump"] = {id=260,recastId=166,command="/ja"},
    ["Presto"] = {id=261,recastId=236,command="/ja"},
    ["Divine Waltz II"] = {id=262,recastId=190,command="/ja"},
    ["Flourishes III"] = {id=263,recastId=226,command="/ja"},
    ["Climactic Flourish"] = {id=264,recastId=226,command="/ja"},
    ["Libra"] = {id=265,recastId=237,command="/ja"},
    ["Tactical Switch"] = {id=266,recastId=213,command="/ja"},
    ["Blood Rage"] = {id=267,recastId=11,command="/ja"},
    ["Impetus"] = {id=269,recastId=31,command="/ja"},
    ["Divine Caress"] = {id=270,recastId=32,command="/ja"},
    ["Sacrosanctity"] = {id=271,recastId=33,command="/ja"},
    ["Enmity Douse"] = {id=272,recastId=34,command="/ja"},
    ["Manawell"] = {id=273,recastId=35,command="/ja"},
    ["Saboteur"] = {id=274,recastId=36,command="/ja"},
    ["Spontaneity"] = {id=275,recastId=37,command="/ja"},
    ["Conspirator"] = {id=276,recastId=40,command="/ja"},
    ["Sepulcher"] = {id=277,recastId=41,command="/ja"},
    ["Palisade"] = {id=278,recastId=42,command="/ja"},
    ["Arcane Crest"] = {id=279,recastId=43,command="/ja"},
    ["Scarlet Delirium"] = {id=280,recastId=44,command="/ja"},
    ["Spur"] = {id=281,recastId=45,command="/ja"},
    ["Run Wild"] = {id=282,recastId=46,command="/ja"},
    ["Tenuto"] = {id=283,recastId=47,command="/ja"},
    ["Marcato"] = {id=284,recastId=48,command="/ja"},
    ["Bounty Shot"] = {id=285,recastId=51,command="/ja"},
    ["Decoy Shot"] = {id=286,recastId=52,command="/ja"},
    ["Hamanoha"] = {id=287,recastId=53,command="/ja"},
    ["Hagakure"] = {id=288,recastId=54,command="/ja"},
    ["Issekigan"] = {id=291,recastId=57,command="/ja"},
    ["Dragon Breaker"] = {id=292,recastId=58,command="/ja"},
    ["Soul Jump"] = {id=293,recastId=167,command="/ja"},
    ["Steady Wing"] = {id=295,recastId=70,command="/ja"},
    ["Mana Cede"] = {id=296,recastId=71,command="/ja"},
    ["Efflux"] = {id=297,recastId=185,command="/ja"},
    ["Unbridled Learning"] = {id=298,recastId=81,command="/ja"},
    ["Triple Shot"] = {id=301,recastId=84,command="/ja"},
    ["Allies' Roll"] = {id=302,recastId=193,command="/ja"},
    ["Miser's Roll"] = {id=303,recastId=193,command="/ja"},
    ["Companion's Roll"] = {id=304,recastId=193,command="/ja"},
    ["Avenger's Roll"] = {id=305,recastId=193,command="/ja"},
    ["Cooldown"] = {id=309,recastId=114,command="/ja"},
    ["Deus Ex Automata"] = {id=310,recastId=115,command="/ja"},
    ["Curing Waltz V"] = {id=311,recastId=189,command="/ja"},
    ["Feather Step"] = {id=312,recastId=220,command="/ja"},
    ["Striking Flourish"] = {id=313,recastId=226,command="/ja"},
    ["Ternary Flourish"] = {id=314,recastId=226,command="/ja"},
    ["Perpetuance"] = {id=316,recastId=231,command="/ja"},
    ["Immanence"] = {id=317,recastId=231,command="/ja"},
    ["Smiting Breath"] = {id=318,recastId=238,command="/ja"},
    ["Restoring Breath"] = {id=319,recastId=239,command="/ja"},
    ["Konzen-ittai"] = {id=320,recastId=132,command="/ja"},
    ["Bully"] = {id=321,recastId=240,command="/ja"},
    ["Maintenance"] = {id=322,recastId=214,command="/ja"},
    ["Brazen Rush"] = {id=323,recastId=254,command="/ja"},
    ["Inner Strength"] = {id=324,recastId=254,command="/ja"},
    ["Asylum"] = {id=325,recastId=254,command="/ja"},
    ["Subtle Sorcery"] = {id=326,recastId=254,command="/ja"},
    ["Stymie"] = {id=327,recastId=254,command="/ja"},
    ["Larceny"] = {id=328,recastId=254,command="/ja"},
    ["Intervene"] = {id=329,recastId=254,command="/ja"},
    ["Soul Enslavement"] = {id=330,recastId=254,command="/ja"},
    ["Unleash"] = {id=331,recastId=254,command="/ja"},
    ["Clarion Call"] = {id=332,recastId=254,command="/ja"},
    ["Overkill"] = {id=333,recastId=254,command="/ja"},
    ["Yaegasumi"] = {id=334,recastId=254,command="/ja"},
    ["Mikage"] = {id=335,recastId=254,command="/ja"},
    ["Fly High"] = {id=336,recastId=254,command="/ja"},
    ["Astral Conduit"] = {id=337,recastId=254,command="/ja"},
    ["Unbridled Wisdom"] = {id=338,recastId=254,command="/ja"},
    ["Cutting Cards"] = {id=339,recastId=254,command="/ja"},
    ["Heady Artifice"] = {id=340,recastId=254,command="/ja"},
    ["Grand Pas"] = {id=341,recastId=254,command="/ja"},
    ["Caper Emissarius"] = {id=342,recastId=254,command="/ja"},
    ["Bolster"] = {id=343,recastId=0,command="/ja"},
    ["Swipe"] = {id=344,recastId=241,command="/ja"},
    ["Full Circle"] = {id=345,recastId=243,command="/ja"},
    ["Lasting Emanation"] = {id=346,recastId=244,command="/ja"},
    ["Ecliptic Attrition"] = {id=347,recastId=244,command="/ja"},
    ["Collimated Fervor"] = {id=348,recastId=245,command="/ja"},
    ["Life Cycle"] = {id=349,recastId=246,command="/ja"},
    ["Blaze of Glory"] = {id=350,recastId=247,command="/ja"},
    ["Dematerialize"] = {id=351,recastId=248,command="/ja"},
    ["Theurgic Focus"] = {id=352,recastId=249,command="/ja"},
    ["Concentric Pulse"] = {id=353,recastId=250,command="/ja"},
    ["Mending Halation"] = {id=354,recastId=251,command="/ja"},
    ["Radial Arcana"] = {id=355,recastId=252,command="/ja"},
    ["Elemental Sforzo"] = {id=356,recastId=0,command="/ja"},
    ["Rune Enchantment"] = {id=357,recastId=92,command="/ja"},
    ["Ignis"] = {id=358,recastId=10,command="/ja"},
    ["Gelus"] = {id=359,recastId=10,command="/ja"},
    ["Flabra"] = {id=360,recastId=10,command="/ja"},
    ["Tellus"] = {id=361,recastId=10,command="/ja"},
    ["Sulpor"] = {id=362,recastId=10,command="/ja"},
    ["Unda"] = {id=363,recastId=10,command="/ja"},
    ["Lux"] = {id=364,recastId=10,command="/ja"},
    ["Tenebrae"] = {id=365,recastId=10,command="/ja"},
    ["Vallation"] = {id=366,recastId=23,command="/ja"},
    ["Swordplay"] = {id=367,recastId=24,command="/ja"},
    ["Lunge"] = {id=368,recastId=25,command="/ja"},
    ["Pflug"] = {id=369,recastId=59,command="/ja"},
    ["Embolden"] = {id=370,recastId=72,command="/ja"},
    ["Valiance"] = {id=371,recastId=113,command="/ja"},
    ["Gambit"] = {id=372,recastId=116,command="/ja"},
    ["Liement"] = {id=373,recastId=117,command="/ja"},
    ["One for All"] = {id=374,recastId=118,command="/ja"},
    ["Rayke"] = {id=375,recastId=119,command="/ja"},
    ["Battuta"] = {id=376,recastId=120,command="/ja"},
    ["Widened Compass"] = {id=377,recastId=130,command="/ja"},
    ["Odyllic Subterfuge"] = {id=378,recastId=131,command="/ja"},
    ["Ward"] = {id=379,recastId=142,command="/ja"},
    ["Effusion"] = {id=380,recastId=143,command="/ja"},
    ["Chocobo Jig II"] = {id=381,recastId=218,command="/ja"},
    ["Relinquish"] = {id=382,recastId=253,command="/ja"},
    ["Vivacious Pulse"] = {id=383,recastId=242,command="/ja"},
    ["Contradance"] = {id=384,recastId=229,command="/ja"},
    ["Apogee"] = {id=385,recastId=108,command="/ja"},
    ["Entrust"] = {id=386,recastId=93,command="/ja"},
    ["Bestial Loyalty"] = {id=387,recastId=94,command="/ja"},
    ["Cascade"] = {id=388,recastId=12,command="/ja"},
    ["Consume Mana"] = {id=389,recastId=95,command="/ja"},
    ["Naturalist's Roll"] = {id=390,recastId=193,command="/ja"},
    ["Runeist's Roll"] = {id=391,recastId=193,command="/ja"},
    ["Crooked Cards"] = {id=392,recastId=96,command="/ja"},
    ["Spirit Bond"] = {id=393,recastId=149,command="/ja"},
    ["Majesty"] = {id=394,recastId=150,command="/ja"},
    ["Hover Shot"] = {id=395,recastId=151,command="/ja"},
    ["Healing Ruby"] = {id=512,recastId=174,command="/ja"},
    ["Poison Nails"] = {id=513,recastId=173,command="/ja"},
    ["Shining Ruby"] = {id=514,recastId=174,command="/ja"},
    ["Glittering Ruby"] = {id=515,recastId=174,command="/ja"},
    ["Meteorite"] = {id=516,recastId=173,command="/ja"},
    ["Healing Ruby II"] = {id=517,recastId=174,command="/ja"},
    ["Searing Light"] = {id=518,recastId=173,command="/ja"},
    ["Holy Mist"] = {id=519,recastId=173,command="/ja"},
    ["Soothing Ruby"] = {id=520,recastId=174,command="/ja"},
    ["Regal Scratch"] = {id=521,recastId=173,command="/ja"},
    ["Mewing Lullaby"] = {id=522,recastId=174,command="/ja"},
    ["Eerie Eye"] = {id=523,recastId=174,command="/ja"},
    ["Level ? Holy"] = {id=524,recastId=173,command="/ja"},
    ["Raise II"] = {id=525,recastId=174,command="/ja"},
    ["Reraise II"] = {id=526,recastId=174,command="/ja"},
    ["Altana's Favor"] = {id=527,recastId=174,command="/ja"},
    ["Moonlit Charge"] = {id=528,recastId=173,command="/ja"},
    ["Crescent Fang"] = {id=529,recastId=173,command="/ja"},
    ["Lunar Cry"] = {id=530,recastId=174,command="/ja"},
    ["Lunar Roar"] = {id=531,recastId=174,command="/ja"},
    ["Ecliptic Growl"] = {id=532,recastId=174,command="/ja"},
    ["Ecliptic Howl"] = {id=533,recastId=174,command="/ja"},
    ["Eclipse Bite"] = {id=534,recastId=173,command="/ja"},
    ["Howling Moon"] = {id=536,recastId=173,command="/ja"},
    ["Lunar Bay"] = {id=537,recastId=173,command="/ja"},
    ["Heavenward Howl"] = {id=538,recastId=174,command="/ja"},
    ["Impact"] = {id=539,recastId=173,command="/ja"},
    ["Punch"] = {id=544,recastId=173,command="/ja"},
    ["Fire II"] = {id=545,recastId=173,command="/ja"},
    ["Burning Strike"] = {id=546,recastId=173,command="/ja"},
    ["Double Punch"] = {id=547,recastId=173,command="/ja"},
    ["Crimson Howl"] = {id=548,recastId=174,command="/ja"},
    ["Fire IV"] = {id=549,recastId=173,command="/ja"},
    ["Flaming Crush"] = {id=550,recastId=173,command="/ja"},
    ["Meteor Strike"] = {id=551,recastId=173,command="/ja"},
    ["Inferno"] = {id=552,recastId=173,command="/ja"},
    ["Inferno Howl"] = {id=553,recastId=174,command="/ja"},
    ["Conflag Strike"] = {id=554,recastId=173,command="/ja"},
    ["Rock Throw"] = {id=560,recastId=173,command="/ja"},
    ["Stone II"] = {id=561,recastId=173,command="/ja"},
    ["Rock Buster"] = {id=562,recastId=173,command="/ja"},
    ["Megalith Throw"] = {id=563,recastId=173,command="/ja"},
    ["Earthen Ward"] = {id=564,recastId=174,command="/ja"},
    ["Stone IV"] = {id=565,recastId=173,command="/ja"},
    ["Mountain Buster"] = {id=566,recastId=173,command="/ja"},
    ["Geocrush"] = {id=567,recastId=173,command="/ja"},
    ["Earthen Fury"] = {id=568,recastId=173,command="/ja"},
    ["Earthen Armor"] = {id=569,recastId=174,command="/ja"},
    ["Crag Throw"] = {id=570,recastId=173,command="/ja"},
    ["Barracuda Dive"] = {id=576,recastId=173,command="/ja"},
    ["Water II"] = {id=577,recastId=173,command="/ja"},
    ["Tail Whip"] = {id=578,recastId=173,command="/ja"},
    ["Spring Water"] = {id=579,recastId=174,command="/ja"},
    ["Slowga"] = {id=580,recastId=174,command="/ja"},
    ["Water IV"] = {id=581,recastId=173,command="/ja"},
    ["Spinning Dive"] = {id=582,recastId=173,command="/ja"},
    ["Grand Fall"] = {id=583,recastId=173,command="/ja"},
    ["Tidal Wave"] = {id=584,recastId=173,command="/ja"},
    ["Tidal Roar"] = {id=585,recastId=174,command="/ja"},
    ["Soothing Current"] = {id=586,recastId=174,command="/ja"},
    ["Claw"] = {id=592,recastId=173,command="/ja"},
    ["Aero II"] = {id=593,recastId=173,command="/ja"},
    ["Whispering Wind"] = {id=594,recastId=174,command="/ja"},
    ["Hastega"] = {id=595,recastId=174,command="/ja"},
    ["Aerial Armor"] = {id=596,recastId=174,command="/ja"},
    ["Aero IV"] = {id=597,recastId=173,command="/ja"},
    ["Predator Claws"] = {id=598,recastId=173,command="/ja"},
    ["Wind Blade"] = {id=599,recastId=173,command="/ja"},
    ["Aerial Blast"] = {id=600,recastId=173,command="/ja"},
    ["Fleet Wind"] = {id=601,recastId=174,command="/ja"},
    ["Hastega II"] = {id=602,recastId=174,command="/ja"},
    ["Axe Kick"] = {id=608,recastId=173,command="/ja"},
    ["Blizzard II"] = {id=609,recastId=173,command="/ja"},
    ["Frost Armor"] = {id=610,recastId=174,command="/ja"},
    ["Sleepga"] = {id=611,recastId=174,command="/ja"},
    ["Double Slap"] = {id=612,recastId=173,command="/ja"},
    ["Blizzard IV"] = {id=613,recastId=173,command="/ja"},
    ["Rush"] = {id=614,recastId=173,command="/ja"},
    ["Heavenly Strike"] = {id=615,recastId=173,command="/ja"},
    ["Diamond Dust"] = {id=616,recastId=173,command="/ja"},
    ["Diamond Storm"] = {id=617,recastId=174,command="/ja"},
    ["Crystal Blessing"] = {id=618,recastId=174,command="/ja"},
    ["Shock Strike"] = {id=624,recastId=173,command="/ja"},
    ["Thunder II"] = {id=625,recastId=173,command="/ja"},
    ["Rolling Thunder"] = {id=626,recastId=174,command="/ja"},
    ["Thunderspark"] = {id=627,recastId=173,command="/ja"},
    ["Lightning Armor"] = {id=628,recastId=174,command="/ja"},
    ["Thunder IV"] = {id=629,recastId=173,command="/ja"},
    ["Chaotic Strike"] = {id=630,recastId=173,command="/ja"},
    ["Thunderstorm"] = {id=631,recastId=173,command="/ja"},
    ["Judgment Bolt"] = {id=632,recastId=173,command="/ja"},
    ["Shock Squall"] = {id=633,recastId=174,command="/ja"},
    ["Volt Strike"] = {id=634,recastId=173,command="/ja"},
    ["Healing Breath IV"] = {id=639,recastId=0,command="/ja"},
    ["Healing Breath"] = {id=640,recastId=0,command="/ja"},
    ["Healing Breath II"] = {id=641,recastId=0,command="/ja"},
    ["Healing Breath III"] = {id=642,recastId=0,command="/ja"},
    ["Remove Poison"] = {id=643,recastId=0,command="/ja"},
    ["Remove Blindness"] = {id=644,recastId=0,command="/ja"},
    ["Remove Paralysis"] = {id=645,recastId=0,command="/ja"},
    ["Flame Breath"] = {id=646,recastId=0,command="/ja"},
    ["Frost Breath"] = {id=647,recastId=0,command="/ja"},
    ["Gust Breath"] = {id=648,recastId=0,command="/ja"},
    ["Sand Breath"] = {id=649,recastId=0,command="/ja"},
    ["Lightning Breath"] = {id=650,recastId=0,command="/ja"},
    ["Hydro Breath"] = {id=651,recastId=0,command="/ja"},
    ["Super Climb"] = {id=652,recastId=0,command="/ja"},
    ["Remove Curse"] = {id=653,recastId=0,command="/ja"},
    ["Remove Disease"] = {id=654,recastId=0,command="/ja"},
    ["Camisado"] = {id=656,recastId=173,command="/ja"},
    ["Somnolence"] = {id=657,recastId=174,command="/ja"},
    ["Nightmare"] = {id=658,recastId=174,command="/ja"},
    ["Ultimate Terror"] = {id=659,recastId=174,command="/ja"},
    ["Noctoshield"] = {id=660,recastId=174,command="/ja"},
    ["Dream Shroud"] = {id=661,recastId=174,command="/ja"},
    ["Nether Blast"] = {id=662,recastId=173,command="/ja"},
    ["Cacodemonia"] = {id=663,recastId=173,command="/ja"},
    ["Ruinous Omen"] = {id=664,recastId=173,command="/ja"},
    ["Night Terror"] = {id=665,recastId=173,command="/ja"},
    ["Pavor Nocturnus"] = {id=666,recastId=174,command="/ja"},
    ["Blindside"] = {id=667,recastId=173,command="/ja"},
    ["Deconstruction"] = {id=668,recastId=0,command="/ja"},
    ["Chronoshift"] = {id=669,recastId=0,command="/ja"},
    ["Zantetsuken"] = {id=670,recastId=0,command="/ja"},
    ["Perfect Defense"] = {id=671,recastId=0,command="/ja"},
    ["Foot Kick"] = {id=672,recastId=102,command="/ja"},
    ["Dust Cloud"] = {id=673,recastId=102,command="/ja"},
    ["Whirl Claws"] = {id=674,recastId=102,command="/ja"},
    ["Head Butt"] = {id=675,recastId=102,command="/ja"},
    ["Dream Flower"] = {id=676,recastId=102,command="/ja"},
    ["Wild Oats"] = {id=677,recastId=102,command="/ja"},
    ["Leaf Dagger"] = {id=678,recastId=102,command="/ja"},
    ["Scream"] = {id=679,recastId=102,command="/ja"},
    ["Roar"] = {id=680,recastId=102,command="/ja"},
    ["Razor Fang"] = {id=681,recastId=102,command="/ja"},
    ["Claw Cyclone"] = {id=682,recastId=102,command="/ja"},
    ["Tail Blow"] = {id=683,recastId=102,command="/ja"},
    ["Fireball"] = {id=684,recastId=102,command="/ja"},
    ["Blockhead"] = {id=685,recastId=102,command="/ja"},
    ["Brain Crush"] = {id=686,recastId=102,command="/ja"},
    ["Infrasonics"] = {id=687,recastId=102,command="/ja"},
    ["Secretion"] = {id=688,recastId=102,command="/ja"},
    ["Lamb Chop"] = {id=689,recastId=102,command="/ja"},
    ["Rage"] = {id=690,recastId=102,command="/ja"},
    ["Sheep Charge"] = {id=691,recastId=102,command="/ja"},
    ["Sheep Song"] = {id=692,recastId=102,command="/ja"},
    ["Bubble Shower"] = {id=693,recastId=102,command="/ja"},
    ["Bubble Curtain"] = {id=694,recastId=102,command="/ja"},
    ["Big Scissors"] = {id=695,recastId=102,command="/ja"},
    ["Scissor Guard"] = {id=696,recastId=102,command="/ja"},
    ["Metallic Body"] = {id=697,recastId=102,command="/ja"},
    ["Needleshot"] = {id=698,recastId=102,command="/ja"},
    ["??? Needles"] = {id=699,recastId=102,command="/ja"},
    ["Frogkick"] = {id=700,recastId=102,command="/ja"},
    ["Spore"] = {id=701,recastId=102,command="/ja"},
    ["Queasyshroom"] = {id=702,recastId=102,command="/ja"},
    ["Numbshroom"] = {id=703,recastId=102,command="/ja"},
    ["Shakeshroom"] = {id=704,recastId=102,command="/ja"},
    ["Silence Gas"] = {id=705,recastId=102,command="/ja"},
    ["Dark Spore"] = {id=706,recastId=102,command="/ja"},
    ["Power Attack"] = {id=707,recastId=102,command="/ja"},
    ["Hi-Freq Field"] = {id=708,recastId=102,command="/ja"},
    ["Rhino Attack"] = {id=709,recastId=102,command="/ja"},
    ["Rhino Guard"] = {id=710,recastId=102,command="/ja"},
    ["Spoil"] = {id=711,recastId=102,command="/ja"},
    ["Cursed Sphere"] = {id=712,recastId=102,command="/ja"},
    ["Venom"] = {id=713,recastId=102,command="/ja"},
    ["Sandblast"] = {id=714,recastId=102,command="/ja"},
    ["Sandpit"] = {id=715,recastId=102,command="/ja"},
    ["Venom Spray"] = {id=716,recastId=102,command="/ja"},
    ["Mandibular Bite"] = {id=717,recastId=102,command="/ja"},
    ["Soporific"] = {id=718,recastId=102,command="/ja"},
    ["Gloeosuccus"] = {id=719,recastId=102,command="/ja"},
    ["Palsy Pollen"] = {id=720,recastId=102,command="/ja"},
    ["Geist Wall"] = {id=721,recastId=102,command="/ja"},
    ["Numbing Noise"] = {id=722,recastId=102,command="/ja"},
    ["Nimble Snap"] = {id=723,recastId=102,command="/ja"},
    ["Cyclotail"] = {id=724,recastId=102,command="/ja"},
    ["Toxic Spit"] = {id=725,recastId=102,command="/ja"},
    ["Double Claw"] = {id=726,recastId=102,command="/ja"},
    ["Grapple"] = {id=727,recastId=102,command="/ja"},
    ["Spinning Top"] = {id=728,recastId=102,command="/ja"},
    ["Filamented Hold"] = {id=729,recastId=102,command="/ja"},
    ["Chaotic Eye"] = {id=730,recastId=102,command="/ja"},
    ["Blaster"] = {id=731,recastId=102,command="/ja"},
    ["Suction"] = {id=732,recastId=102,command="/ja"},
    ["Drainkiss"] = {id=733,recastId=102,command="/ja"},
    ["Snow Cloud"] = {id=734,recastId=102,command="/ja"},
    ["Wild Carrot"] = {id=735,recastId=102,command="/ja"},
    ["Sudden Lunge"] = {id=736,recastId=102,command="/ja"},
    ["Spiral Spin"] = {id=737,recastId=102,command="/ja"},
    ["Noisome Powder"] = {id=738,recastId=102,command="/ja"},
    ["Acid Mist"] = {id=740,recastId=102,command="/ja"},
    ["TP Drainkiss"] = {id=741,recastId=102,command="/ja"},
    ["Scythe Tail"] = {id=743,recastId=102,command="/ja"},
    ["Ripper Fang"] = {id=744,recastId=102,command="/ja"},
    ["Chomp Rush"] = {id=745,recastId=102,command="/ja"},
    ["Charged Whisker"] = {id=746,recastId=102,command="/ja"},
    ["Purulent Ooze"] = {id=747,recastId=102,command="/ja"},
    ["Corrosive Ooze"] = {id=748,recastId=102,command="/ja"},
    ["Back Heel"] = {id=749,recastId=102,command="/ja"},
    ["Jettatura"] = {id=750,recastId=102,command="/ja"},
    ["Choke Breath"] = {id=751,recastId=102,command="/ja"},
    ["Fantod"] = {id=752,recastId=102,command="/ja"},
    ["Tortoise Stomp"] = {id=753,recastId=102,command="/ja"},
    ["Harden Shell"] = {id=754,recastId=102,command="/ja"},
    ["Aqua Breath"] = {id=755,recastId=102,command="/ja"},
    ["Wing Slap"] = {id=756,recastId=102,command="/ja"},
    ["Beak Lunge"] = {id=757,recastId=102,command="/ja"},
    ["Intimidate"] = {id=758,recastId=102,command="/ja"},
    ["Recoil Dive"] = {id=759,recastId=102,command="/ja"},
    ["Water Wall"] = {id=760,recastId=102,command="/ja"},
    ["Sensilla Blades"] = {id=761,recastId=102,command="/ja"},
    ["Tegmina Buffet"] = {id=762,recastId=102,command="/ja"},
    ["Molting Plumage"] = {id=763,recastId=102,command="/ja"},
    ["Swooping Frenzy"] = {id=764,recastId=102,command="/ja"},
    ["Sweeping Gouge"] = {id=765,recastId=102,command="/ja"},
    ["Zealous Snort"] = {id=766,recastId=102,command="/ja"},
    ["Pentapeck"] = {id=767,recastId=102,command="/ja"},
    ["Tickling Tendrils"] = {id=768,recastId=102,command="/ja"},
    ["Stink Bomb"] = {id=769,recastId=102,command="/ja"},
    ["Nectarous Deluge"] = {id=770,recastId=102,command="/ja"},
    ["Nepenthic Plunge"] = {id=771,recastId=102,command="/ja"},
    ["Somersault"] = {id=772,recastId=102,command="/ja"},
    ["Pacifying Ruby"] = {id=773,recastId=174,command="/ja"},
    ["Foul Waters"] = {id=774,recastId=102,command="/ja"},
    ["Pestilent Plume"] = {id=775,recastId=102,command="/ja"},
    ["Pecking Flurry"] = {id=776,recastId=102,command="/ja"},
    ["Sickle Slash"] = {id=777,recastId=102,command="/ja"},
    ["Acid Spray"] = {id=778,recastId=102,command="/ja"},
    ["Spider Web"] = {id=779,recastId=102,command="/ja"},
    ["Regal Gash"] = {id=780,recastId=173,command="/ja"},
    ["Infected Leech"] = {id=781,recastId=102,command="/ja"},
    ["Gloom Spray"] = {id=782,recastId=102,command="/ja"},
    ["Disembowel"] = {id=786,recastId=102,command="/ja"},
    ["Extirpating Salvo"] = {id=787,recastId=102,command="/ja"},
    ["Venom Shower"] = {id=788,recastId=102,command="/ja"},
    ["Mega Scissors"] = {id=789,recastId=102,command="/ja"},
    ["Frenzied Rage"] = {id=790,recastId=102,command="/ja"},
    ["Rhinowrecker"] = {id=791,recastId=102,command="/ja"},
    ["Fluid Toss"] = {id=792,recastId=102,command="/ja"},
    ["Fluid Spread"] = {id=793,recastId=102,command="/ja"},
    ["Digest"] = {id=794,recastId=102,command="/ja"},
    ["Crossthrash"] = {id=795,recastId=102,command="/ja"},
    ["Predatory Glare"] = {id=796,recastId=102,command="/ja"},
    ["Hoof Volley"] = {id=797,recastId=102,command="/ja"},
    ["Nihility Song"] = {id=798,recastId=102,command="/ja"},
    ["Clarsach Call"] = {id=960,recastId=173,command="/ja"},
    ["Welt"] = {id=961,recastId=173,command="/ja"},
    ["Katabatic Blades"] = {id=962,recastId=174,command="/ja"},
    ["Lunatic Voice"] = {id=963,recastId=174,command="/ja"},
    ["Roundhouse"] = {id=964,recastId=173,command="/ja"},
    ["Chinook"] = {id=965,recastId=174,command="/ja"},
    ["Bitter Elegy"] = {id=966,recastId=174,command="/ja"},
    ["Sonic Buffet"] = {id=967,recastId=173,command="/ja"},
    ["Tornado II"] = {id=968,recastId=173,command="/ja"},
    ["Wind's Blessing"] = {id=969,recastId=174,command="/ja"},
    ["Hysteric Assault"] = {id=970,recastId=173,command="/ja"},
    ["Cure"] = {id=1,recastId=1,command="/ma"},
    ["Cure II"] = {id=2,recastId=2,command="/ma"},
    ["Cure III"] = {id=3,recastId=3,command="/ma"},
    ["Cure IV"] = {id=4,recastId=4,command="/ma"},
    ["Cure V"] = {id=5,recastId=5,command="/ma"},
    ["Cure VI"] = {id=6,recastId=6,command="/ma"},
    ["Curaga"] = {id=7,recastId=7,command="/ma"},
    ["Curaga II"] = {id=8,recastId=8,command="/ma"},
    ["Curaga III"] = {id=9,recastId=9,command="/ma"},
    ["Curaga IV"] = {id=10,recastId=10,command="/ma"},
    ["Curaga V"] = {id=11,recastId=11,command="/ma"},
    ["Raise"] = {id=12,recastId=12,command="/ma"},
    ["Raise II"] = {id=13,recastId=13,command="/ma"},
    ["Poisona"] = {id=14,recastId=14,command="/ma"},
    ["Paralyna"] = {id=15,recastId=15,command="/ma"},
    ["Blindna"] = {id=16,recastId=16,command="/ma"},
    ["Silena"] = {id=17,recastId=17,command="/ma"},
    ["Stona"] = {id=18,recastId=18,command="/ma"},
    ["Viruna"] = {id=19,recastId=19,command="/ma"},
    ["Cursna"] = {id=20,recastId=20,command="/ma"},
    ["Holy"] = {id=21,recastId=21,command="/ma"},
    ["Holy II"] = {id=22,recastId=22,command="/ma"},
    ["Dia"] = {id=23,recastId=23,command="/ma"},
    ["Dia II"] = {id=24,recastId=24,command="/ma"},
    ["Dia III"] = {id=25,recastId=25,command="/ma"},
    ["Dia IV"] = {id=26,recastId=26,command="/ma"},
    ["Dia V"] = {id=27,recastId=27,command="/ma"},
    ["Banish"] = {id=28,recastId=28,command="/ma"},
    ["Banish II"] = {id=29,recastId=29,command="/ma"},
    ["Banish III"] = {id=30,recastId=30,command="/ma"},
    ["Banish IV"] = {id=31,recastId=31,command="/ma"},
    ["Banish V"] = {id=32,recastId=32,command="/ma"},
    ["Diaga"] = {id=33,recastId=33,command="/ma"},
    ["Diaga II"] = {id=34,recastId=34,command="/ma"},
    ["Diaga III"] = {id=35,recastId=35,command="/ma"},
    ["Diaga IV"] = {id=36,recastId=36,command="/ma"},
    ["Diaga V"] = {id=37,recastId=37,command="/ma"},
    ["Banishga"] = {id=38,recastId=38,command="/ma"},
    ["Banishga II"] = {id=39,recastId=39,command="/ma"},
    ["Banishga III"] = {id=40,recastId=40,command="/ma"},
    ["Banishga IV"] = {id=41,recastId=41,command="/ma"},
    ["Banishga V"] = {id=42,recastId=42,command="/ma"},
    ["Protect"] = {id=43,recastId=43,command="/ma"},
    ["Protect II"] = {id=44,recastId=44,command="/ma"},
    ["Protect III"] = {id=45,recastId=45,command="/ma"},
    ["Protect IV"] = {id=46,recastId=46,command="/ma"},
    ["Protect V"] = {id=47,recastId=47,command="/ma"},
    ["Shell"] = {id=48,recastId=48,command="/ma"},
    ["Shell II"] = {id=49,recastId=49,command="/ma"},
    ["Shell III"] = {id=50,recastId=50,command="/ma"},
    ["Shell IV"] = {id=51,recastId=51,command="/ma"},
    ["Shell V"] = {id=52,recastId=52,command="/ma"},
    ["Blink"] = {id=53,recastId=53,command="/ma"},
    ["Stoneskin"] = {id=54,recastId=54,command="/ma"},
    ["Aquaveil"] = {id=55,recastId=55,command="/ma"},
    ["Slow"] = {id=56,recastId=56,command="/ma"},
    ["Haste"] = {id=57,recastId=57,command="/ma"},
    ["Paralyze"] = {id=58,recastId=58,command="/ma"},
    ["Silence"] = {id=59,recastId=59,command="/ma"},
    ["Barfire"] = {id=60,recastId=60,command="/ma"},
    ["Barblizzard"] = {id=61,recastId=61,command="/ma"},
    ["Baraero"] = {id=62,recastId=62,command="/ma"},
    ["Barstone"] = {id=63,recastId=63,command="/ma"},
    ["Barthunder"] = {id=64,recastId=64,command="/ma"},
    ["Barwater"] = {id=65,recastId=65,command="/ma"},
    ["Barfira"] = {id=66,recastId=66,command="/ma"},
    ["Barblizzara"] = {id=67,recastId=67,command="/ma"},
    ["Baraera"] = {id=68,recastId=68,command="/ma"},
    ["Barstonra"] = {id=69,recastId=69,command="/ma"},
    ["Barthundra"] = {id=70,recastId=70,command="/ma"},
    ["Barwatera"] = {id=71,recastId=71,command="/ma"},
    ["Barsleep"] = {id=72,recastId=72,command="/ma"},
    ["Barpoison"] = {id=73,recastId=73,command="/ma"},
    ["Barparalyze"] = {id=74,recastId=74,command="/ma"},
    ["Barblind"] = {id=75,recastId=75,command="/ma"},
    ["Barsilence"] = {id=76,recastId=76,command="/ma"},
    ["Barpetrify"] = {id=77,recastId=77,command="/ma"},
    ["Barvirus"] = {id=78,recastId=78,command="/ma"},
    ["Slow II"] = {id=79,recastId=79,command="/ma"},
    ["Paralyze II"] = {id=80,recastId=80,command="/ma"},
    ["Recall-Jugner"] = {id=81,recastId=81,command="/ma"},
    ["Recall-Pashh"] = {id=82,recastId=82,command="/ma"},
    ["Recall-Meriph"] = {id=83,recastId=83,command="/ma"},
    ["Baramnesia"] = {id=84,recastId=84,command="/ma"},
    ["Baramnesra"] = {id=85,recastId=85,command="/ma"},
    ["Barsleepra"] = {id=86,recastId=86,command="/ma"},
    ["Barpoisonra"] = {id=87,recastId=87,command="/ma"},
    ["Barparalyzra"] = {id=88,recastId=88,command="/ma"},
    ["Barblindra"] = {id=89,recastId=89,command="/ma"},
    ["Barsilencera"] = {id=90,recastId=90,command="/ma"},
    ["Barpetra"] = {id=91,recastId=91,command="/ma"},
    ["Barvira"] = {id=92,recastId=92,command="/ma"},
    ["Cura"] = {id=93,recastId=93,command="/ma"},
    ["Sacrifice"] = {id=94,recastId=94,command="/ma"},
    ["Esuna"] = {id=95,recastId=95,command="/ma"},
    ["Auspice"] = {id=96,recastId=96,command="/ma"},
    ["Reprisal"] = {id=97,recastId=97,command="/ma"},
    ["Repose"] = {id=98,recastId=98,command="/ma"},
    ["Sandstorm"] = {id=99,recastId=99,command="/ma"},
    ["Enfire"] = {id=100,recastId=100,command="/ma"},
    ["Enblizzard"] = {id=101,recastId=101,command="/ma"},
    ["Enaero"] = {id=102,recastId=102,command="/ma"},
    ["Enstone"] = {id=103,recastId=103,command="/ma"},
    ["Enthunder"] = {id=104,recastId=104,command="/ma"},
    ["Enwater"] = {id=105,recastId=105,command="/ma"},
    ["Phalanx"] = {id=106,recastId=106,command="/ma"},
    ["Phalanx II"] = {id=107,recastId=107,command="/ma"},
    ["Regen"] = {id=108,recastId=108,command="/ma"},
    ["Refresh"] = {id=109,recastId=109,command="/ma"},
    ["Regen II"] = {id=110,recastId=110,command="/ma"},
    ["Regen III"] = {id=111,recastId=111,command="/ma"},
    ["Flash"] = {id=112,recastId=112,command="/ma"},
    ["Rainstorm"] = {id=113,recastId=113,command="/ma"},
    ["Windstorm"] = {id=114,recastId=114,command="/ma"},
    ["Firestorm"] = {id=115,recastId=115,command="/ma"},
    ["Hailstorm"] = {id=116,recastId=116,command="/ma"},
    ["Thunderstorm"] = {id=117,recastId=117,command="/ma"},
    ["Voidstorm"] = {id=118,recastId=118,command="/ma"},
    ["Aurorastorm"] = {id=119,recastId=119,command="/ma"},
    ["Teleport-Yhoat"] = {id=120,recastId=120,command="/ma"},
    ["Teleport-Altep"] = {id=121,recastId=121,command="/ma"},
    ["Teleport-Holla"] = {id=122,recastId=122,command="/ma"},
    ["Teleport-Dem"] = {id=123,recastId=123,command="/ma"},
    ["Teleport-Mea"] = {id=124,recastId=124,command="/ma"},
    ["Protectra"] = {id=125,recastId=125,command="/ma"},
    ["Protectra II"] = {id=126,recastId=126,command="/ma"},
    ["Protectra III"] = {id=127,recastId=127,command="/ma"},
    ["Protectra IV"] = {id=128,recastId=128,command="/ma"},
    ["Protectra V"] = {id=129,recastId=129,command="/ma"},
    ["Shellra"] = {id=130,recastId=130,command="/ma"},
    ["Shellra II"] = {id=131,recastId=131,command="/ma"},
    ["Shellra III"] = {id=132,recastId=132,command="/ma"},
    ["Shellra IV"] = {id=133,recastId=133,command="/ma"},
    ["Shellra V"] = {id=134,recastId=134,command="/ma"},
    ["Reraise"] = {id=135,recastId=135,command="/ma"},
    ["Invisible"] = {id=136,recastId=136,command="/ma"},
    ["Sneak"] = {id=137,recastId=137,command="/ma"},
    ["Deodorize"] = {id=138,recastId=138,command="/ma"},
    ["Teleport-Vahzl"] = {id=139,recastId=139,command="/ma"},
    ["Raise III"] = {id=140,recastId=140,command="/ma"},
    ["Reraise II"] = {id=141,recastId=141,command="/ma"},
    ["Reraise III"] = {id=142,recastId=142,command="/ma"},
    ["Erase"] = {id=143,recastId=143,command="/ma"},
    ["Fire"] = {id=144,recastId=144,command="/ma"},
    ["Fire II"] = {id=145,recastId=145,command="/ma"},
    ["Fire III"] = {id=146,recastId=146,command="/ma"},
    ["Fire IV"] = {id=147,recastId=147,command="/ma"},
    ["Fire V"] = {id=148,recastId=148,command="/ma"},
    ["Blizzard"] = {id=149,recastId=149,command="/ma"},
    ["Blizzard II"] = {id=150,recastId=150,command="/ma"},
    ["Blizzard III"] = {id=151,recastId=151,command="/ma"},
    ["Blizzard IV"] = {id=152,recastId=152,command="/ma"},
    ["Blizzard V"] = {id=153,recastId=153,command="/ma"},
    ["Aero"] = {id=154,recastId=154,command="/ma"},
    ["Aero II"] = {id=155,recastId=155,command="/ma"},
    ["Aero III"] = {id=156,recastId=156,command="/ma"},
    ["Aero IV"] = {id=157,recastId=157,command="/ma"},
    ["Aero V"] = {id=158,recastId=158,command="/ma"},
    ["Stone"] = {id=159,recastId=159,command="/ma"},
    ["Stone II"] = {id=160,recastId=160,command="/ma"},
    ["Stone III"] = {id=161,recastId=161,command="/ma"},
    ["Stone IV"] = {id=162,recastId=162,command="/ma"},
    ["Stone V"] = {id=163,recastId=163,command="/ma"},
    ["Thunder"] = {id=164,recastId=164,command="/ma"},
    ["Thunder II"] = {id=165,recastId=165,command="/ma"},
    ["Thunder III"] = {id=166,recastId=166,command="/ma"},
    ["Thunder IV"] = {id=167,recastId=167,command="/ma"},
    ["Thunder V"] = {id=168,recastId=168,command="/ma"},
    ["Water"] = {id=169,recastId=169,command="/ma"},
    ["Water II"] = {id=170,recastId=170,command="/ma"},
    ["Water III"] = {id=171,recastId=171,command="/ma"},
    ["Water IV"] = {id=172,recastId=172,command="/ma"},
    ["Water V"] = {id=173,recastId=173,command="/ma"},
    ["Firaga"] = {id=174,recastId=174,command="/ma"},
    ["Firaga II"] = {id=175,recastId=175,command="/ma"},
    ["Firaga III"] = {id=176,recastId=176,command="/ma"},
    ["Firaga IV"] = {id=177,recastId=177,command="/ma"},
    ["Firaga V"] = {id=178,recastId=178,command="/ma"},
    ["Blizzaga"] = {id=179,recastId=179,command="/ma"},
    ["Blizzaga II"] = {id=180,recastId=180,command="/ma"},
    ["Blizzaga III"] = {id=181,recastId=181,command="/ma"},
    ["Blizzaga IV"] = {id=182,recastId=182,command="/ma"},
    ["Blizzaga V"] = {id=183,recastId=183,command="/ma"},
    ["Aeroga"] = {id=184,recastId=184,command="/ma"},
    ["Aeroga II"] = {id=185,recastId=185,command="/ma"},
    ["Aeroga III"] = {id=186,recastId=186,command="/ma"},
    ["Aeroga IV"] = {id=187,recastId=187,command="/ma"},
    ["Aeroga V"] = {id=188,recastId=188,command="/ma"},
    ["Stonega"] = {id=189,recastId=189,command="/ma"},
    ["Stonega II"] = {id=190,recastId=190,command="/ma"},
    ["Stonega III"] = {id=191,recastId=191,command="/ma"},
    ["Stonega IV"] = {id=192,recastId=192,command="/ma"},
    ["Stonega V"] = {id=193,recastId=193,command="/ma"},
    ["Thundaga"] = {id=194,recastId=194,command="/ma"},
    ["Thundaga II"] = {id=195,recastId=195,command="/ma"},
    ["Thundaga III"] = {id=196,recastId=196,command="/ma"},
    ["Thundaga IV"] = {id=197,recastId=197,command="/ma"},
    ["Thundaga V"] = {id=198,recastId=198,command="/ma"},
    ["Waterga"] = {id=199,recastId=199,command="/ma"},
    ["Waterga II"] = {id=200,recastId=200,command="/ma"},
    ["Waterga III"] = {id=201,recastId=201,command="/ma"},
    ["Waterga IV"] = {id=202,recastId=202,command="/ma"},
    ["Waterga V"] = {id=203,recastId=203,command="/ma"},
    ["Flare"] = {id=204,recastId=204,command="/ma"},
    ["Flare II"] = {id=205,recastId=205,command="/ma"},
    ["Freeze"] = {id=206,recastId=206,command="/ma"},
    ["Freeze II"] = {id=207,recastId=207,command="/ma"},
    ["Tornado"] = {id=208,recastId=208,command="/ma"},
    ["Tornado II"] = {id=209,recastId=209,command="/ma"},
    ["Quake"] = {id=210,recastId=210,command="/ma"},
    ["Quake II"] = {id=211,recastId=211,command="/ma"},
    ["Burst"] = {id=212,recastId=212,command="/ma"},
    ["Burst II"] = {id=213,recastId=213,command="/ma"},
    ["Flood"] = {id=214,recastId=214,command="/ma"},
    ["Flood II"] = {id=215,recastId=215,command="/ma"},
    ["Gravity"] = {id=216,recastId=216,command="/ma"},
    ["Gravity II"] = {id=217,recastId=217,command="/ma"},
    ["Meteor"] = {id=218,recastId=218,command="/ma"},
    ["Comet"] = {id=219,recastId=219,command="/ma"},
    ["Poison"] = {id=220,recastId=220,command="/ma"},
    ["Poison II"] = {id=221,recastId=221,command="/ma"},
    ["Poison III"] = {id=222,recastId=222,command="/ma"},
    ["Poison IV"] = {id=223,recastId=223,command="/ma"},
    ["Poison V"] = {id=224,recastId=224,command="/ma"},
    ["Poisonga"] = {id=225,recastId=225,command="/ma"},
    ["Poisonga II"] = {id=226,recastId=226,command="/ma"},
    ["Poisonga III"] = {id=227,recastId=227,command="/ma"},
    ["Poisonga IV"] = {id=228,recastId=228,command="/ma"},
    ["Poisonga V"] = {id=229,recastId=229,command="/ma"},
    ["Bio"] = {id=230,recastId=230,command="/ma"},
    ["Bio II"] = {id=231,recastId=231,command="/ma"},
    ["Bio III"] = {id=232,recastId=232,command="/ma"},
    ["Bio IV"] = {id=233,recastId=233,command="/ma"},
    ["Bio V"] = {id=234,recastId=234,command="/ma"},
    ["Burn"] = {id=235,recastId=235,command="/ma"},
    ["Frost"] = {id=236,recastId=236,command="/ma"},
    ["Choke"] = {id=237,recastId=237,command="/ma"},
    ["Rasp"] = {id=238,recastId=238,command="/ma"},
    ["Shock"] = {id=239,recastId=239,command="/ma"},
    ["Drown"] = {id=240,recastId=240,command="/ma"},
    ["Retrace"] = {id=241,recastId=241,command="/ma"},
    ["Absorb-ACC"] = {id=242,recastId=242,command="/ma"},
    ["Absorb-Attri"] = {id=243,recastId=243,command="/ma"},
    ["Meteor II"] = {id=244,recastId=244,command="/ma"},
    ["Drain"] = {id=245,recastId=245,command="/ma"},
    ["Drain II"] = {id=246,recastId=246,command="/ma"},
    ["Aspir"] = {id=247,recastId=247,command="/ma"},
    ["Aspir II"] = {id=248,recastId=248,command="/ma"},
    ["Blaze Spikes"] = {id=249,recastId=249,command="/ma"},
    ["Ice Spikes"] = {id=250,recastId=250,command="/ma"},
    ["Shock Spikes"] = {id=251,recastId=251,command="/ma"},
    ["Stun"] = {id=252,recastId=252,command="/ma"},
    ["Sleep"] = {id=253,recastId=253,command="/ma"},
    ["Blind"] = {id=254,recastId=254,command="/ma"},
    ["Break"] = {id=255,recastId=255,command="/ma"},
    ["Virus"] = {id=256,recastId=256,command="/ma"},
    ["Curse"] = {id=257,recastId=257,command="/ma"},
    ["Bind"] = {id=258,recastId=258,command="/ma"},
    ["Sleep II"] = {id=259,recastId=259,command="/ma"},
    ["Dispel"] = {id=260,recastId=260,command="/ma"},
    ["Warp"] = {id=261,recastId=261,command="/ma"},
    ["Warp II"] = {id=262,recastId=262,command="/ma"},
    ["Escape"] = {id=263,recastId=263,command="/ma"},
    ["Tractor"] = {id=264,recastId=264,command="/ma"},
    ["Tractor II"] = {id=265,recastId=265,command="/ma"},
    ["Absorb-STR"] = {id=266,recastId=266,command="/ma"},
    ["Absorb-DEX"] = {id=267,recastId=267,command="/ma"},
    ["Absorb-VIT"] = {id=268,recastId=268,command="/ma"},
    ["Absorb-AGI"] = {id=269,recastId=269,command="/ma"},
    ["Absorb-INT"] = {id=270,recastId=270,command="/ma"},
    ["Absorb-MND"] = {id=271,recastId=271,command="/ma"},
    ["Absorb-CHR"] = {id=272,recastId=272,command="/ma"},
    ["Sleepga"] = {id=273,recastId=273,command="/ma"},
    ["Sleepga II"] = {id=274,recastId=274,command="/ma"},
    ["Absorb-TP"] = {id=275,recastId=275,command="/ma"},
    ["Blind II"] = {id=276,recastId=276,command="/ma"},
    ["Dread Spikes"] = {id=277,recastId=277,command="/ma"},
    ["Geohelix"] = {id=278,recastId=278,command="/ma"},
    ["Hydrohelix"] = {id=279,recastId=279,command="/ma"},
    ["Anemohelix"] = {id=280,recastId=280,command="/ma"},
    ["Pyrohelix"] = {id=281,recastId=281,command="/ma"},
    ["Cryohelix"] = {id=282,recastId=282,command="/ma"},
    ["Ionohelix"] = {id=283,recastId=283,command="/ma"},
    ["Noctohelix"] = {id=284,recastId=284,command="/ma"},
    ["Luminohelix"] = {id=285,recastId=285,command="/ma"},
    ["Addle"] = {id=286,recastId=286,command="/ma"},
    ["Klimaform"] = {id=287,recastId=287,command="/ma"},
    ["Fire Spirit"] = {id=288,recastId=288,command="/ma"},
    ["Ice Spirit"] = {id=289,recastId=289,command="/ma"},
    ["Air Spirit"] = {id=290,recastId=290,command="/ma"},
    ["Earth Spirit"] = {id=291,recastId=291,command="/ma"},
    ["Thunder Spirit"] = {id=292,recastId=292,command="/ma"},
    ["Water Spirit"] = {id=293,recastId=293,command="/ma"},
    ["Light Spirit"] = {id=294,recastId=294,command="/ma"},
    ["Dark Spirit"] = {id=295,recastId=295,command="/ma"},
    ["Carbuncle"] = {id=296,recastId=296,command="/ma"},
    ["Fenrir"] = {id=297,recastId=297,command="/ma"},
    ["Ifrit"] = {id=298,recastId=298,command="/ma"},
    ["Titan"] = {id=299,recastId=299,command="/ma"},
    ["Leviathan"] = {id=300,recastId=300,command="/ma"},
    ["Garuda"] = {id=301,recastId=301,command="/ma"},
    ["Shiva"] = {id=302,recastId=302,command="/ma"},
    ["Ramuh"] = {id=303,recastId=303,command="/ma"},
    ["Diabolos"] = {id=304,recastId=304,command="/ma"},
    ["Odin"] = {id=305,recastId=305,command="/ma"},
    ["Alexander"] = {id=306,recastId=306,command="/ma"},
    ["Cait Sith"] = {id=307,recastId=307,command="/ma"},
    ["Animus Augeo"] = {id=308,recastId=308,command="/ma"},
    ["Animus Minuo"] = {id=309,recastId=309,command="/ma"},
    ["Enlight"] = {id=310,recastId=310,command="/ma"},
    ["Endark"] = {id=311,recastId=311,command="/ma"},
    ["Enfire II"] = {id=312,recastId=312,command="/ma"},
    ["Enblizzard II"] = {id=313,recastId=313,command="/ma"},
    ["Enaero II"] = {id=314,recastId=314,command="/ma"},
    ["Enstone II"] = {id=315,recastId=315,command="/ma"},
    ["Enthunder II"] = {id=316,recastId=316,command="/ma"},
    ["Enwater II"] = {id=317,recastId=317,command="/ma"},
    ["Monomi: Ichi"] = {id=318,recastId=318,command="/ma"},
    ["Aisha: Ichi"] = {id=319,recastId=319,command="/ma"},
    ["Katon: Ichi"] = {id=320,recastId=320,command="/ma"},
    ["Katon: Ni"] = {id=321,recastId=321,command="/ma"},
    ["Katon: San"] = {id=322,recastId=322,command="/ma"},
    ["Hyoton: Ichi"] = {id=323,recastId=323,command="/ma"},
    ["Hyoton: Ni"] = {id=324,recastId=324,command="/ma"},
    ["Hyoton: San"] = {id=325,recastId=325,command="/ma"},
    ["Huton: Ichi"] = {id=326,recastId=326,command="/ma"},
    ["Huton: Ni"] = {id=327,recastId=327,command="/ma"},
    ["Huton: San"] = {id=328,recastId=328,command="/ma"},
    ["Doton: Ichi"] = {id=329,recastId=329,command="/ma"},
    ["Doton: Ni"] = {id=330,recastId=330,command="/ma"},
    ["Doton: San"] = {id=331,recastId=331,command="/ma"},
    ["Raiton: Ichi"] = {id=332,recastId=332,command="/ma"},
    ["Raiton: Ni"] = {id=333,recastId=333,command="/ma"},
    ["Raiton: San"] = {id=334,recastId=334,command="/ma"},
    ["Suiton: Ichi"] = {id=335,recastId=335,command="/ma"},
    ["Suiton: Ni"] = {id=336,recastId=336,command="/ma"},
    ["Suiton: San"] = {id=337,recastId=337,command="/ma"},
    ["Utsusemi: Ichi"] = {id=338,recastId=338,command="/ma"},
    ["Utsusemi: Ni"] = {id=339,recastId=339,command="/ma"},
    ["Utsusemi: San"] = {id=340,recastId=340,command="/ma"},
    ["Jubaku: Ichi"] = {id=341,recastId=341,command="/ma"},
    ["Jubaku: Ni"] = {id=342,recastId=342,command="/ma"},
    ["Jubaku: San"] = {id=343,recastId=343,command="/ma"},
    ["Hojo: Ichi"] = {id=344,recastId=344,command="/ma"},
    ["Hojo: Ni"] = {id=345,recastId=345,command="/ma"},
    ["Hojo: San"] = {id=346,recastId=346,command="/ma"},
    ["Kurayami: Ichi"] = {id=347,recastId=347,command="/ma"},
    ["Kurayami: Ni"] = {id=348,recastId=348,command="/ma"},
    ["Kurayami: San"] = {id=349,recastId=349,command="/ma"},
    ["Dokumori: Ichi"] = {id=350,recastId=350,command="/ma"},
    ["Dokumori: Ni"] = {id=351,recastId=351,command="/ma"},
    ["Dokumori: San"] = {id=352,recastId=352,command="/ma"},
    ["Tonko: Ichi"] = {id=353,recastId=353,command="/ma"},
    ["Tonko: Ni"] = {id=354,recastId=354,command="/ma"},
    ["Siren"] = {id=355,recastId=355,command="/ma"},
    ["Paralyga"] = {id=356,recastId=356,command="/ma"},
    ["Slowga"] = {id=357,recastId=357,command="/ma"},
    ["Hastega"] = {id=358,recastId=358,command="/ma"},
    ["Silencega"] = {id=359,recastId=359,command="/ma"},
    ["Dispelga"] = {id=360,recastId=360,command="/ma"},
    ["Blindga"] = {id=361,recastId=361,command="/ma"},
    ["Bindga"] = {id=362,recastId=362,command="/ma"},
    ["Sleepga"] = {id=363,recastId=363,command="/ma"},
    ["Sleepga II"] = {id=364,recastId=364,command="/ma"},
    ["Breakga"] = {id=365,recastId=365,command="/ma"},
    ["Graviga"] = {id=366,recastId=366,command="/ma"},
    ["Death"] = {id=367,recastId=367,command="/ma"},
    ["Foe Requiem"] = {id=368,recastId=368,command="/ma"},
    ["Foe Requiem II"] = {id=369,recastId=369,command="/ma"},
    ["Foe Requiem III"] = {id=370,recastId=370,command="/ma"},
    ["Foe Requiem IV"] = {id=371,recastId=371,command="/ma"},
    ["Foe Requiem V"] = {id=372,recastId=372,command="/ma"},
    ["Foe Requiem VI"] = {id=373,recastId=373,command="/ma"},
    ["Foe Requiem VII"] = {id=374,recastId=374,command="/ma"},
    ["Foe Requiem VIII"] = {id=375,recastId=375,command="/ma"},
    ["Horde Lullaby"] = {id=376,recastId=376,command="/ma"},
    ["Horde Lullaby II"] = {id=377,recastId=377,command="/ma"},
    ["Army's Paeon"] = {id=378,recastId=378,command="/ma"},
    ["Army's Paeon II"] = {id=379,recastId=379,command="/ma"},
    ["Army's Paeon III"] = {id=380,recastId=380,command="/ma"},
    ["Army's Paeon IV"] = {id=381,recastId=381,command="/ma"},
    ["Army's Paeon V"] = {id=382,recastId=382,command="/ma"},
    ["Army's Paeon VI"] = {id=383,recastId=383,command="/ma"},
    ["Army's Paeon VII"] = {id=384,recastId=384,command="/ma"},
    ["Army's Paeon VIII"] = {id=385,recastId=385,command="/ma"},
    ["Mage's Ballad"] = {id=386,recastId=386,command="/ma"},
    ["Mage's Ballad II"] = {id=387,recastId=387,command="/ma"},
    ["Mage's Ballad III"] = {id=388,recastId=388,command="/ma"},
    ["Knight's Minne"] = {id=389,recastId=389,command="/ma"},
    ["Knight's Minne II"] = {id=390,recastId=390,command="/ma"},
    ["Knight's Minne III"] = {id=391,recastId=391,command="/ma"},
    ["Knight's Minne IV"] = {id=392,recastId=392,command="/ma"},
    ["Knight's Minne V"] = {id=393,recastId=393,command="/ma"},
    ["Valor Minuet"] = {id=394,recastId=394,command="/ma"},
    ["Valor Minuet II"] = {id=395,recastId=395,command="/ma"},
    ["Valor Minuet III"] = {id=396,recastId=396,command="/ma"},
    ["Valor Minuet IV"] = {id=397,recastId=397,command="/ma"},
    ["Valor Minuet V"] = {id=398,recastId=398,command="/ma"},
    ["Sword Madrigal"] = {id=399,recastId=399,command="/ma"},
    ["Blade Madrigal"] = {id=400,recastId=400,command="/ma"},
    ["Hunter's Prelude"] = {id=401,recastId=401,command="/ma"},
    ["Archer's Prelude"] = {id=402,recastId=402,command="/ma"},
    ["Sheepfoe Mambo"] = {id=403,recastId=403,command="/ma"},
    ["Dragonfoe Mambo"] = {id=404,recastId=404,command="/ma"},
    ["Fowl Aubade"] = {id=405,recastId=405,command="/ma"},
    ["Herb Pastoral"] = {id=406,recastId=406,command="/ma"},
    ["Chocobo Hum"] = {id=407,recastId=407,command="/ma"},
    ["Shining Fantasia"] = {id=408,recastId=408,command="/ma"},
    ["Scop's Operetta"] = {id=409,recastId=409,command="/ma"},
    ["Puppet's Operetta"] = {id=410,recastId=410,command="/ma"},
    ["Jester's Operetta"] = {id=411,recastId=411,command="/ma"},
    ["Gold Capriccio"] = {id=412,recastId=412,command="/ma"},
    ["Devotee Serenade"] = {id=413,recastId=413,command="/ma"},
    ["Warding Round"] = {id=414,recastId=414,command="/ma"},
    ["Goblin Gavotte"] = {id=415,recastId=415,command="/ma"},
    ["Cactuar Fugue"] = {id=416,recastId=416,command="/ma"},
    ["Honor March"] = {id=417,recastId=417,command="/ma"},
    ["Protected Aria"] = {id=418,recastId=418,command="/ma"},
    ["Advancing March"] = {id=419,recastId=419,command="/ma"},
    ["Victory March"] = {id=420,recastId=420,command="/ma"},
    ["Battlefield Elegy"] = {id=421,recastId=421,command="/ma"},
    ["Carnage Elegy"] = {id=422,recastId=422,command="/ma"},
    ["Massacre Elegy"] = {id=423,recastId=423,command="/ma"},
    ["Sinewy Etude"] = {id=424,recastId=424,command="/ma"},
    ["Dextrous Etude"] = {id=425,recastId=425,command="/ma"},
    ["Vivacious Etude"] = {id=426,recastId=426,command="/ma"},
    ["Quick Etude"] = {id=427,recastId=427,command="/ma"},
    ["Learned Etude"] = {id=428,recastId=428,command="/ma"},
    ["Spirited Etude"] = {id=429,recastId=429,command="/ma"},
    ["Enchanting Etude"] = {id=430,recastId=430,command="/ma"},
    ["Herculean Etude"] = {id=431,recastId=431,command="/ma"},
    ["Uncanny Etude"] = {id=432,recastId=432,command="/ma"},
    ["Vital Etude"] = {id=433,recastId=433,command="/ma"},
    ["Swift Etude"] = {id=434,recastId=434,command="/ma"},
    ["Sage Etude"] = {id=435,recastId=435,command="/ma"},
    ["Logical Etude"] = {id=436,recastId=436,command="/ma"},
    ["Bewitching Etude"] = {id=437,recastId=437,command="/ma"},
    ["Fire Carol"] = {id=438,recastId=438,command="/ma"},
    ["Ice Carol"] = {id=439,recastId=439,command="/ma"},
    ["Wind Carol"] = {id=440,recastId=440,command="/ma"},
    ["Earth Carol"] = {id=441,recastId=441,command="/ma"},
    ["Lightning Carol"] = {id=442,recastId=442,command="/ma"},
    ["Water Carol"] = {id=443,recastId=443,command="/ma"},
    ["Light Carol"] = {id=444,recastId=444,command="/ma"},
    ["Dark Carol"] = {id=445,recastId=445,command="/ma"},
    ["Fire Carol II"] = {id=446,recastId=446,command="/ma"},
    ["Ice Carol II"] = {id=447,recastId=447,command="/ma"},
    ["Wind Carol II"] = {id=448,recastId=448,command="/ma"},
    ["Earth Carol II"] = {id=449,recastId=449,command="/ma"},
    ["Lightning Carol II"] = {id=450,recastId=450,command="/ma"},
    ["Water Carol II"] = {id=451,recastId=451,command="/ma"},
    ["Light Carol II"] = {id=452,recastId=452,command="/ma"},
    ["Dark Carol II"] = {id=453,recastId=453,command="/ma"},
    ["Fire Threnody"] = {id=454,recastId=454,command="/ma"},
    ["Ice Threnody"] = {id=455,recastId=455,command="/ma"},
    ["Wind Threnody"] = {id=456,recastId=456,command="/ma"},
    ["Earth Threnody"] = {id=457,recastId=457,command="/ma"},
    ["Ltng. Threnody"] = {id=458,recastId=458,command="/ma"},
    ["Water Threnody"] = {id=459,recastId=459,command="/ma"},
    ["Light Threnody"] = {id=460,recastId=460,command="/ma"},
    ["Dark Threnody"] = {id=461,recastId=461,command="/ma"},
    ["Magic Finale"] = {id=462,recastId=462,command="/ma"},
    ["Foe Lullaby"] = {id=463,recastId=463,command="/ma"},
    ["Goddess's Hymnus"] = {id=464,recastId=464,command="/ma"},
    ["Chocobo Mazurka"] = {id=465,recastId=465,command="/ma"},
    ["Maiden's Virelai"] = {id=466,recastId=466,command="/ma"},
    ["Raptor Mazurka"] = {id=467,recastId=467,command="/ma"},
    ["Foe Sirvente"] = {id=468,recastId=468,command="/ma"},
    ["Adventurer's Dirge"] = {id=469,recastId=469,command="/ma"},
    ["Sentinel's Scherzo"] = {id=470,recastId=470,command="/ma"},
    ["Foe Lullaby II"] = {id=471,recastId=471,command="/ma"},
    ["Pining Nocturne"] = {id=472,recastId=472,command="/ma"},
    ["Refresh II"] = {id=473,recastId=473,command="/ma"},
    ["Cura II"] = {id=474,recastId=474,command="/ma"},
    ["Cura III"] = {id=475,recastId=475,command="/ma"},
    ["Crusade"] = {id=476,recastId=476,command="/ma"},
    ["Regen IV"] = {id=477,recastId=477,command="/ma"},
    ["Embrava"] = {id=478,recastId=478,command="/ma"},
    ["Boost-STR"] = {id=479,recastId=479,command="/ma"},
    ["Boost-DEX"] = {id=480,recastId=480,command="/ma"},
    ["Boost-VIT"] = {id=481,recastId=481,command="/ma"},
    ["Boost-AGI"] = {id=482,recastId=482,command="/ma"},
    ["Boost-INT"] = {id=483,recastId=483,command="/ma"},
    ["Boost-MND"] = {id=484,recastId=484,command="/ma"},
    ["Boost-CHR"] = {id=485,recastId=485,command="/ma"},
    ["Gain-STR"] = {id=486,recastId=486,command="/ma"},
    ["Gain-DEX"] = {id=487,recastId=487,command="/ma"},
    ["Gain-VIT"] = {id=488,recastId=488,command="/ma"},
    ["Gain-AGI"] = {id=489,recastId=489,command="/ma"},
    ["Gain-INT"] = {id=490,recastId=490,command="/ma"},
    ["Gain-MND"] = {id=491,recastId=491,command="/ma"},
    ["Gain-CHR"] = {id=492,recastId=492,command="/ma"},
    ["Temper"] = {id=493,recastId=493,command="/ma"},
    ["Arise"] = {id=494,recastId=494,command="/ma"},
    ["Adloquium"] = {id=495,recastId=495,command="/ma"},
    ["Firaja"] = {id=496,recastId=496,command="/ma"},
    ["Blizzaja"] = {id=497,recastId=497,command="/ma"},
    ["Aeroja"] = {id=498,recastId=498,command="/ma"},
    ["Stoneja"] = {id=499,recastId=499,command="/ma"},
    ["Thundaja"] = {id=500,recastId=500,command="/ma"},
    ["Waterja"] = {id=501,recastId=501,command="/ma"},
    ["Kaustra"] = {id=502,recastId=502,command="/ma"},
    ["Impact"] = {id=503,recastId=503,command="/ma"},
    ["Regen V"] = {id=504,recastId=504,command="/ma"},
    ["Gekka: Ichi"] = {id=505,recastId=505,command="/ma"},
    ["Yain: Ichi"] = {id=506,recastId=506,command="/ma"},
    ["Myoshu: Ichi"] = {id=507,recastId=507,command="/ma"},
    ["Yurin: Ichi"] = {id=508,recastId=508,command="/ma"},
    ["Kakka: Ichi"] = {id=509,recastId=509,command="/ma"},
    ["Migawari: Ichi"] = {id=510,recastId=510,command="/ma"},
    ["Haste II"] = {id=511,recastId=511,command="/ma"},
    ["Venom Shell"] = {id=513,recastId=513,command="/ma"},
    ["Maelstrom"] = {id=515,recastId=515,command="/ma"},
    ["Metallic Body"] = {id=517,recastId=517,command="/ma"},
    ["Screwdriver"] = {id=519,recastId=519,command="/ma"},
    ["MP Drainkiss"] = {id=521,recastId=521,command="/ma"},
    ["Death Ray"] = {id=522,recastId=522,command="/ma"},
    ["Sandspin"] = {id=524,recastId=524,command="/ma"},
    ["Smite of Rage"] = {id=527,recastId=527,command="/ma"},
    ["Bludgeon"] = {id=529,recastId=529,command="/ma"},
    ["Refueling"] = {id=530,recastId=530,command="/ma"},
    ["Ice Break"] = {id=531,recastId=531,command="/ma"},
    ["Blitzstrahl"] = {id=532,recastId=532,command="/ma"},
    ["Self-Destruct"] = {id=533,recastId=533,command="/ma"},
    ["Mysterious Light"] = {id=534,recastId=534,command="/ma"},
    ["Cold Wave"] = {id=535,recastId=535,command="/ma"},
    ["Poison Breath"] = {id=536,recastId=536,command="/ma"},
    ["Stinking Gas"] = {id=537,recastId=537,command="/ma"},
    ["Memento Mori"] = {id=538,recastId=538,command="/ma"},
    ["Terror Touch"] = {id=539,recastId=539,command="/ma"},
    ["Spinal Cleave"] = {id=540,recastId=540,command="/ma"},
    ["Blood Saber"] = {id=541,recastId=541,command="/ma"},
    ["Digest"] = {id=542,recastId=542,command="/ma"},
    ["Mandibular Bite"] = {id=543,recastId=543,command="/ma"},
    ["Cursed Sphere"] = {id=544,recastId=544,command="/ma"},
    ["Sickle Slash"] = {id=545,recastId=545,command="/ma"},
    ["Cocoon"] = {id=547,recastId=547,command="/ma"},
    ["Filamented Hold"] = {id=548,recastId=548,command="/ma"},
    ["Pollen"] = {id=549,recastId=549,command="/ma"},
    ["Power Attack"] = {id=551,recastId=551,command="/ma"},
    ["Death Scissors"] = {id=554,recastId=554,command="/ma"},
    ["Magnetite Cloud"] = {id=555,recastId=555,command="/ma"},
    ["Eyes On Me"] = {id=557,recastId=557,command="/ma"},
    ["Frenetic Rip"] = {id=560,recastId=560,command="/ma"},
    ["Frightful Roar"] = {id=561,recastId=561,command="/ma"},
    ["Hecatomb Wave"] = {id=563,recastId=563,command="/ma"},
    ["Body Slam"] = {id=564,recastId=564,command="/ma"},
    ["Radiant Breath"] = {id=565,recastId=565,command="/ma"},
    ["Helldive"] = {id=567,recastId=567,command="/ma"},
    ["Jet Stream"] = {id=569,recastId=569,command="/ma"},
    ["Blood Drain"] = {id=570,recastId=570,command="/ma"},
    ["Sound Blast"] = {id=572,recastId=572,command="/ma"},
    ["Feather Tickle"] = {id=573,recastId=573,command="/ma"},
    ["Feather Barrier"] = {id=574,recastId=574,command="/ma"},
    ["Jettatura"] = {id=575,recastId=575,command="/ma"},
    ["Yawn"] = {id=576,recastId=576,command="/ma"},
    ["Foot Kick"] = {id=577,recastId=577,command="/ma"},
    ["Wild Carrot"] = {id=578,recastId=578,command="/ma"},
    ["Voracious Trunk"] = {id=579,recastId=579,command="/ma"},
    ["Healing Breeze"] = {id=581,recastId=581,command="/ma"},
    ["Chaotic Eye"] = {id=582,recastId=582,command="/ma"},
    ["Sheep Song"] = {id=584,recastId=584,command="/ma"},
    ["Ram Charge"] = {id=585,recastId=585,command="/ma"},
    ["Claw Cyclone"] = {id=587,recastId=587,command="/ma"},
    ["Lowing"] = {id=588,recastId=588,command="/ma"},
    ["Dimensional Death"] = {id=589,recastId=589,command="/ma"},
    ["Heat Breath"] = {id=591,recastId=591,command="/ma"},
    ["Blank Gaze"] = {id=592,recastId=592,command="/ma"},
    ["Magic Fruit"] = {id=593,recastId=593,command="/ma"},
    ["Uppercut"] = {id=594,recastId=594,command="/ma"},
    ["1000 Needles"] = {id=595,recastId=595,command="/ma"},
    ["Pinecone Bomb"] = {id=596,recastId=596,command="/ma"},
    ["Sprout Smack"] = {id=597,recastId=597,command="/ma"},
    ["Soporific"] = {id=598,recastId=598,command="/ma"},
    ["Queasyshroom"] = {id=599,recastId=599,command="/ma"},
    ["Wild Oats"] = {id=603,recastId=603,command="/ma"},
    ["Bad Breath"] = {id=604,recastId=604,command="/ma"},
    ["Geist Wall"] = {id=605,recastId=605,command="/ma"},
    ["Awful Eye"] = {id=606,recastId=606,command="/ma"},
    ["Frost Breath"] = {id=608,recastId=608,command="/ma"},
    ["Infrasonics"] = {id=610,recastId=610,command="/ma"},
    ["Disseverment"] = {id=611,recastId=611,command="/ma"},
    ["Actinic Burst"] = {id=612,recastId=612,command="/ma"},
    ["Reactor Cool"] = {id=613,recastId=613,command="/ma"},
    ["Saline Coat"] = {id=614,recastId=614,command="/ma"},
    ["Plasma Charge"] = {id=615,recastId=615,command="/ma"},
    ["Temporal Shift"] = {id=616,recastId=616,command="/ma"},
    ["Vertical Cleave"] = {id=617,recastId=617,command="/ma"},
    ["Blastbomb"] = {id=618,recastId=618,command="/ma"},
    ["Battle Dance"] = {id=620,recastId=620,command="/ma"},
    ["Sandspray"] = {id=621,recastId=621,command="/ma"},
    ["Grand Slam"] = {id=622,recastId=622,command="/ma"},
    ["Head Butt"] = {id=623,recastId=623,command="/ma"},
    ["Bomb Toss"] = {id=626,recastId=626,command="/ma"},
    ["Frypan"] = {id=628,recastId=628,command="/ma"},
    ["Flying Hip Press"] = {id=629,recastId=629,command="/ma"},
    ["Hydro Shot"] = {id=631,recastId=631,command="/ma"},
    ["Diamondhide"] = {id=632,recastId=632,command="/ma"},
    ["Enervation"] = {id=633,recastId=633,command="/ma"},
    ["Light of Penance"] = {id=634,recastId=634,command="/ma"},
    ["Warm-Up"] = {id=636,recastId=636,command="/ma"},
    ["Firespit"] = {id=637,recastId=637,command="/ma"},
    ["Feather Storm"] = {id=638,recastId=638,command="/ma"},
    ["Tail Slap"] = {id=640,recastId=640,command="/ma"},
    ["Hysteric Barrage"] = {id=641,recastId=641,command="/ma"},
    ["Amplification"] = {id=642,recastId=642,command="/ma"},
    ["Cannonball"] = {id=643,recastId=643,command="/ma"},
    ["Mind Blast"] = {id=644,recastId=644,command="/ma"},
    ["Exuviation"] = {id=645,recastId=645,command="/ma"},
    ["Magic Hammer"] = {id=646,recastId=646,command="/ma"},
    ["Zephyr Mantle"] = {id=647,recastId=647,command="/ma"},
    ["Regurgitation"] = {id=648,recastId=648,command="/ma"},
    ["Seedspray"] = {id=650,recastId=650,command="/ma"},
    ["Corrosive Ooze"] = {id=651,recastId=651,command="/ma"},
    ["Spiral Spin"] = {id=652,recastId=652,command="/ma"},
    ["Asuran Claws"] = {id=653,recastId=653,command="/ma"},
    ["Sub-zero Smash"] = {id=654,recastId=654,command="/ma"},
    ["Triumphant Roar"] = {id=655,recastId=655,command="/ma"},
    ["Acrid Stream"] = {id=656,recastId=656,command="/ma"},
    ["Blazing Bound"] = {id=657,recastId=657,command="/ma"},
    ["Plenilune Embrace"] = {id=658,recastId=658,command="/ma"},
    ["Demoralizing Roar"] = {id=659,recastId=659,command="/ma"},
    ["Cimicine Discharge"] = {id=660,recastId=660,command="/ma"},
    ["Animating Wail"] = {id=661,recastId=661,command="/ma"},
    ["Battery Charge"] = {id=662,recastId=662,command="/ma"},
    ["Leafstorm"] = {id=663,recastId=663,command="/ma"},
    ["Regeneration"] = {id=664,recastId=664,command="/ma"},
    ["Final Sting"] = {id=665,recastId=665,command="/ma"},
    ["Goblin Rush"] = {id=666,recastId=666,command="/ma"},
    ["Vanity Dive"] = {id=667,recastId=667,command="/ma"},
    ["Magic Barrier"] = {id=668,recastId=668,command="/ma"},
    ["Whirl of Rage"] = {id=669,recastId=669,command="/ma"},
    ["Benthic Typhoon"] = {id=670,recastId=670,command="/ma"},
    ["Auroral Drape"] = {id=671,recastId=671,command="/ma"},
    ["Osmosis"] = {id=672,recastId=672,command="/ma"},
    ["Quad. Continuum"] = {id=673,recastId=673,command="/ma"},
    ["Fantod"] = {id=674,recastId=674,command="/ma"},
    ["Thermal Pulse"] = {id=675,recastId=675,command="/ma"},
    ["Empty Thrash"] = {id=677,recastId=677,command="/ma"},
    ["Dream Flower"] = {id=678,recastId=678,command="/ma"},
    ["Occultation"] = {id=679,recastId=679,command="/ma"},
    ["Charged Whisker"] = {id=680,recastId=680,command="/ma"},
    ["Winds of Promy."] = {id=681,recastId=681,command="/ma"},
    ["Delta Thrust"] = {id=682,recastId=682,command="/ma"},
    ["Evryone. Grudge"] = {id=683,recastId=683,command="/ma"},
    ["Reaving Wind"] = {id=684,recastId=684,command="/ma"},
    ["Barrier Tusk"] = {id=685,recastId=685,command="/ma"},
    ["Mortal Ray"] = {id=686,recastId=686,command="/ma"},
    ["Water Bomb"] = {id=687,recastId=687,command="/ma"},
    ["Heavy Strike"] = {id=688,recastId=688,command="/ma"},
    ["Dark Orb"] = {id=689,recastId=689,command="/ma"},
    ["White Wind"] = {id=690,recastId=690,command="/ma"},
    ["Sudden Lunge"] = {id=692,recastId=692,command="/ma"},
    ["Quadrastrike"] = {id=693,recastId=693,command="/ma"},
    ["Vapor Spray"] = {id=694,recastId=694,command="/ma"},
    ["Thunder Breath"] = {id=695,recastId=695,command="/ma"},
    ["O. Counterstance"] = {id=696,recastId=696,command="/ma"},
    ["Amorphic Spikes"] = {id=697,recastId=697,command="/ma"},
    ["Wind Breath"] = {id=698,recastId=698,command="/ma"},
    ["Barbed Crescent"] = {id=699,recastId=699,command="/ma"},
    ["Nat. Meditation"] = {id=700,recastId=700,command="/ma"},
    ["Tem. Upheaval"] = {id=701,recastId=701,command="/ma"},
    ["Rending Deluge"] = {id=702,recastId=702,command="/ma"},
    ["Embalming Earth"] = {id=703,recastId=703,command="/ma"},
    ["Paralyzing Triad"] = {id=704,recastId=704,command="/ma"},
    ["Foul Waters"] = {id=705,recastId=705,command="/ma"},
    ["Glutinous Dart"] = {id=706,recastId=706,command="/ma"},
    ["Retinal Glare"] = {id=707,recastId=707,command="/ma"},
    ["Subduction"] = {id=708,recastId=708,command="/ma"},
    ["Thrashing Assault"] = {id=709,recastId=709,command="/ma"},
    ["Erratic Flutter"] = {id=710,recastId=710,command="/ma"},
    ["Restoral"] = {id=711,recastId=711,command="/ma"},
    ["Rail Cannon"] = {id=712,recastId=712,command="/ma"},
    ["Diffusion Ray"] = {id=713,recastId=713,command="/ma"},
    ["Sinker Drill"] = {id=714,recastId=714,command="/ma"},
    ["Molting Plumage"] = {id=715,recastId=715,command="/ma"},
    ["Nectarous Deluge"] = {id=716,recastId=716,command="/ma"},
    ["Sweeping Gouge"] = {id=717,recastId=717,command="/ma"},
    ["Atra. Libations"] = {id=718,recastId=718,command="/ma"},
    ["Searing Tempest"] = {id=719,recastId=719,command="/ma"},
    ["Spectral Floe"] = {id=720,recastId=720,command="/ma"},
    ["Anvil Lightning"] = {id=721,recastId=721,command="/ma"},
    ["Entomb"] = {id=722,recastId=722,command="/ma"},
    ["Saurian Slide"] = {id=723,recastId=723,command="/ma"},
    ["Palling Salvo"] = {id=724,recastId=724,command="/ma"},
    ["Blinding Fulgor"] = {id=725,recastId=725,command="/ma"},
    ["Scouring Spate"] = {id=726,recastId=726,command="/ma"},
    ["Silent Storm"] = {id=727,recastId=727,command="/ma"},
    ["Tenebral Crush"] = {id=728,recastId=728,command="/ma"},
    ["Thunderbolt"] = {id=736,recastId=736,command="/ma"},
    ["Harden Shell"] = {id=737,recastId=737,command="/ma"},
    ["Absolute Terror"] = {id=738,recastId=738,command="/ma"},
    ["Gates of Hades"] = {id=739,recastId=739,command="/ma"},
    ["Tourbillion"] = {id=740,recastId=740,command="/ma"},
    ["Pyric Bulwark"] = {id=741,recastId=741,command="/ma"},
    ["Bilgestorm"] = {id=742,recastId=742,command="/ma"},
    ["Bloodrake"] = {id=743,recastId=743,command="/ma"},
    ["Droning Whirlwind"] = {id=744,recastId=744,command="/ma"},
    ["Carcharian Verve"] = {id=745,recastId=745,command="/ma"},
    ["Blistering Roar"] = {id=746,recastId=746,command="/ma"},
    ["Uproot"] = {id=747,recastId=747,command="/ma"},
    ["Crashing Thunder"] = {id=748,recastId=748,command="/ma"},
    ["Polar Roar"] = {id=749,recastId=749,command="/ma"},
    ["Mighty Guard"] = {id=750,recastId=750,command="/ma"},
    ["Cruel Joke"] = {id=751,recastId=751,command="/ma"},
    ["Cesspool"] = {id=752,recastId=752,command="/ma"},
    ["Tearing Gust"] = {id=753,recastId=753,command="/ma"},
    ["Indi-Regen"] = {id=768,recastId=768,command="/ma"},
    ["Indi-Poison"] = {id=769,recastId=769,command="/ma"},
    ["Indi-Refresh"] = {id=770,recastId=770,command="/ma"},
    ["Indi-Haste"] = {id=771,recastId=771,command="/ma"},
    ["Indi-STR"] = {id=772,recastId=772,command="/ma"},
    ["Indi-DEX"] = {id=773,recastId=773,command="/ma"},
    ["Indi-VIT"] = {id=774,recastId=774,command="/ma"},
    ["Indi-AGI"] = {id=775,recastId=775,command="/ma"},
    ["Indi-INT"] = {id=776,recastId=776,command="/ma"},
    ["Indi-MND"] = {id=777,recastId=777,command="/ma"},
    ["Indi-CHR"] = {id=778,recastId=778,command="/ma"},
    ["Indi-Fury"] = {id=779,recastId=779,command="/ma"},
    ["Indi-Barrier"] = {id=780,recastId=780,command="/ma"},
    ["Indi-Acumen"] = {id=781,recastId=781,command="/ma"},
    ["Indi-Fend"] = {id=782,recastId=782,command="/ma"},
    ["Indi-Precision"] = {id=783,recastId=783,command="/ma"},
    ["Indi-Voidance"] = {id=784,recastId=784,command="/ma"},
    ["Indi-Focus"] = {id=785,recastId=785,command="/ma"},
    ["Indi-Attunement"] = {id=786,recastId=786,command="/ma"},
    ["Indi-Wilt"] = {id=787,recastId=787,command="/ma"},
    ["Indi-Frailty"] = {id=788,recastId=788,command="/ma"},
    ["Indi-Fade"] = {id=789,recastId=789,command="/ma"},
    ["Indi-Malaise"] = {id=790,recastId=790,command="/ma"},
    ["Indi-Slip"] = {id=791,recastId=791,command="/ma"},
    ["Indi-Torpor"] = {id=792,recastId=792,command="/ma"},
    ["Indi-Vex"] = {id=793,recastId=793,command="/ma"},
    ["Indi-Languor"] = {id=794,recastId=794,command="/ma"},
    ["Indi-Slow"] = {id=795,recastId=795,command="/ma"},
    ["Indi-Paralysis"] = {id=796,recastId=796,command="/ma"},
    ["Indi-Gravity"] = {id=797,recastId=797,command="/ma"},
    ["Geo-Regen"] = {id=798,recastId=798,command="/ma"},
    ["Geo-Poison"] = {id=799,recastId=799,command="/ma"},
    ["Geo-Refresh"] = {id=800,recastId=800,command="/ma"},
    ["Geo-Haste"] = {id=801,recastId=801,command="/ma"},
    ["Geo-STR"] = {id=802,recastId=802,command="/ma"},
    ["Geo-DEX"] = {id=803,recastId=803,command="/ma"},
    ["Geo-VIT"] = {id=804,recastId=804,command="/ma"},
    ["Geo-AGI"] = {id=805,recastId=805,command="/ma"},
    ["Geo-INT"] = {id=806,recastId=806,command="/ma"},
    ["Geo-MND"] = {id=807,recastId=807,command="/ma"},
    ["Geo-CHR"] = {id=808,recastId=808,command="/ma"},
    ["Geo-Fury"] = {id=809,recastId=809,command="/ma"},
    ["Geo-Barrier"] = {id=810,recastId=810,command="/ma"},
    ["Geo-Acumen"] = {id=811,recastId=811,command="/ma"},
    ["Geo-Fend"] = {id=812,recastId=812,command="/ma"},
    ["Geo-Precision"] = {id=813,recastId=813,command="/ma"},
    ["Geo-Voidance"] = {id=814,recastId=814,command="/ma"},
    ["Geo-Focus"] = {id=815,recastId=815,command="/ma"},
    ["Geo-Attunement"] = {id=816,recastId=816,command="/ma"},
    ["Geo-Wilt"] = {id=817,recastId=817,command="/ma"},
    ["Geo-Frailty"] = {id=818,recastId=818,command="/ma"},
    ["Geo-Fade"] = {id=819,recastId=819,command="/ma"},
    ["Geo-Malaise"] = {id=820,recastId=820,command="/ma"},
    ["Geo-Slip"] = {id=821,recastId=821,command="/ma"},
    ["Geo-Torpor"] = {id=822,recastId=822,command="/ma"},
    ["Geo-Vex"] = {id=823,recastId=823,command="/ma"},
    ["Geo-Languor"] = {id=824,recastId=824,command="/ma"},
    ["Geo-Slow"] = {id=825,recastId=825,command="/ma"},
    ["Geo-Paralysis"] = {id=826,recastId=826,command="/ma"},
    ["Geo-Gravity"] = {id=827,recastId=827,command="/ma"},
    ["Fira"] = {id=828,recastId=828,command="/ma"},
    ["Fira II"] = {id=829,recastId=829,command="/ma"},
    ["Blizzara"] = {id=830,recastId=830,command="/ma"},
    ["Blizzara II"] = {id=831,recastId=831,command="/ma"},
    ["Aera"] = {id=832,recastId=832,command="/ma"},
    ["Aera II"] = {id=833,recastId=833,command="/ma"},
    ["Stonera"] = {id=834,recastId=834,command="/ma"},
    ["Stonera II"] = {id=835,recastId=835,command="/ma"},
    ["Thundara"] = {id=836,recastId=836,command="/ma"},
    ["Thundara II"] = {id=837,recastId=837,command="/ma"},
    ["Watera"] = {id=838,recastId=838,command="/ma"},
    ["Watera II"] = {id=839,recastId=839,command="/ma"},
    ["Foil"] = {id=840,recastId=840,command="/ma"},
    ["Distract"] = {id=841,recastId=841,command="/ma"},
    ["Distract II"] = {id=842,recastId=842,command="/ma"},
    ["Frazzle"] = {id=843,recastId=843,command="/ma"},
    ["Frazzle II"] = {id=844,recastId=844,command="/ma"},
    ["Flurry"] = {id=845,recastId=845,command="/ma"},
    ["Flurry II"] = {id=846,recastId=846,command="/ma"},
    ["Atomos"] = {id=847,recastId=847,command="/ma"},
    ["Reraise IV"] = {id=848,recastId=848,command="/ma"},
    ["Fire VI"] = {id=849,recastId=849,command="/ma"},
    ["Blizzard VI"] = {id=850,recastId=850,command="/ma"},
    ["Aero VI"] = {id=851,recastId=851,command="/ma"},
    ["Stone VI"] = {id=852,recastId=852,command="/ma"},
    ["Thunder VI"] = {id=853,recastId=853,command="/ma"},
    ["Water VI"] = {id=854,recastId=854,command="/ma"},
    ["Enlight II"] = {id=855,recastId=855,command="/ma"},
    ["Endark II"] = {id=856,recastId=856,command="/ma"},
    ["Sandstorm II"] = {id=857,recastId=857,command="/ma"},
    ["Rainstorm II"] = {id=858,recastId=858,command="/ma"},
    ["Windstorm II"] = {id=859,recastId=859,command="/ma"},
    ["Firestorm II"] = {id=860,recastId=860,command="/ma"},
    ["Hailstorm II"] = {id=861,recastId=861,command="/ma"},
    ["Thunderstorm II"] = {id=862,recastId=862,command="/ma"},
    ["Voidstorm II"] = {id=863,recastId=863,command="/ma"},
    ["Aurorastorm II"] = {id=864,recastId=864,command="/ma"},
    ["Fira III"] = {id=865,recastId=865,command="/ma"},
    ["Blizzara III"] = {id=866,recastId=866,command="/ma"},
    ["Aera III"] = {id=867,recastId=867,command="/ma"},
    ["Stonera III"] = {id=868,recastId=868,command="/ma"},
    ["Thundara III"] = {id=869,recastId=869,command="/ma"},
    ["Watera III"] = {id=870,recastId=870,command="/ma"},
    ["Fire Threnody II"] = {id=871,recastId=871,command="/ma"},
    ["Ice Threnody II"] = {id=872,recastId=872,command="/ma"},
    ["Wind Threnody II"] = {id=873,recastId=873,command="/ma"},
    ["Earth Threnody II"] = {id=874,recastId=874,command="/ma"},
    ["Ltng. Threnody II"] = {id=875,recastId=875,command="/ma"},
    ["Water Threnody II"] = {id=876,recastId=876,command="/ma"},
    ["Light Threnody II"] = {id=877,recastId=877,command="/ma"},
    ["Dark Threnody II"] = {id=878,recastId=878,command="/ma"},
    ["Inundation"] = {id=879,recastId=879,command="/ma"},
    ["Drain III"] = {id=880,recastId=880,command="/ma"},
    ["Aspir III"] = {id=881,recastId=881,command="/ma"},
    ["Distract III"] = {id=882,recastId=882,command="/ma"},
    ["Frazzle III"] = {id=883,recastId=883,command="/ma"},
    ["Addle II"] = {id=884,recastId=884,command="/ma"},
    ["Geohelix II"] = {id=885,recastId=885,command="/ma"},
    ["Hydrohelix II"] = {id=886,recastId=886,command="/ma"},
    ["Anemohelix II"] = {id=887,recastId=887,command="/ma"},
    ["Pyrohelix II"] = {id=888,recastId=888,command="/ma"},
    ["Cryohelix II"] = {id=889,recastId=889,command="/ma"},
    ["Ionohelix II"] = {id=890,recastId=890,command="/ma"},
    ["Noctohelix II"] = {id=891,recastId=891,command="/ma"},
    ["Luminohelix II"] = {id=892,recastId=892,command="/ma"},
    ["Full Cure"] = {id=893,recastId=893,command="/ma"},
    ["Refresh III"] = {id=894,recastId=894,command="/ma"},
    ["Temper II"] = {id=895,recastId=895,command="/ma"},
    ["Shantotto"] = {id=896,recastId=896,command="/ma"},
    ["Naji"] = {id=897,recastId=897,command="/ma"},
    ["Kupipi"] = {id=898,recastId=898,command="/ma"},
    ["Excenmille"] = {id=899,recastId=899,command="/ma"},
    ["Ayame"] = {id=900,recastId=900,command="/ma"},
    ["Nanaa Mihgo"] = {id=901,recastId=901,command="/ma"},
    ["Curilla"] = {id=902,recastId=902,command="/ma"},
    ["Volker"] = {id=903,recastId=903,command="/ma"},
    ["Ajido-Marujido"] = {id=904,recastId=904,command="/ma"},
    ["Trion"] = {id=905,recastId=905,command="/ma"},
    ["Zeid"] = {id=906,recastId=906,command="/ma"},
    ["Lion"] = {id=907,recastId=907,command="/ma"},
    ["Tenzen"] = {id=908,recastId=908,command="/ma"},
    ["Mihli Aliapoh"] = {id=909,recastId=909,command="/ma"},
    ["Valaineral"] = {id=910,recastId=910,command="/ma"},
    ["Joachim"] = {id=911,recastId=911,command="/ma"},
    ["Naja Salaheem"] = {id=912,recastId=912,command="/ma"},
    ["Prishe"] = {id=913,recastId=913,command="/ma"},
    ["Ulmia"] = {id=914,recastId=914,command="/ma"},
    ["Shikaree Z"] = {id=915,recastId=915,command="/ma"},
    ["Cherukiki"] = {id=916,recastId=916,command="/ma"},
    ["Iron Eater"] = {id=917,recastId=917,command="/ma"},
    ["Gessho"] = {id=918,recastId=918,command="/ma"},
    ["Gadalar"] = {id=919,recastId=919,command="/ma"},
    ["Rainemard"] = {id=920,recastId=920,command="/ma"},
    ["Ingrid"] = {id=921,recastId=921,command="/ma"},
    ["Lehko Habhoka"] = {id=922,recastId=922,command="/ma"},
    ["Nashmeira"] = {id=923,recastId=923,command="/ma"},
    ["Zazarg"] = {id=924,recastId=924,command="/ma"},
    ["Ovjang"] = {id=925,recastId=925,command="/ma"},
    ["Mnejing"] = {id=926,recastId=926,command="/ma"},
    ["Sakura"] = {id=927,recastId=927,command="/ma"},
    ["Luzaf"] = {id=928,recastId=928,command="/ma"},
    ["Najelith"] = {id=929,recastId=929,command="/ma"},
    ["Aldo"] = {id=930,recastId=930,command="/ma"},
    ["Moogle"] = {id=931,recastId=931,command="/ma"},
    ["Fablinix"] = {id=932,recastId=932,command="/ma"},
    ["Maat"] = {id=933,recastId=933,command="/ma"},
    ["D. Shantotto"] = {id=934,recastId=934,command="/ma"},
    ["Star Sibyl"] = {id=935,recastId=935,command="/ma"},
    ["Karaha-Baruha"] = {id=936,recastId=936,command="/ma"},
    ["Cid"] = {id=937,recastId=937,command="/ma"},
    ["Gilgamesh"] = {id=938,recastId=938,command="/ma"},
    ["Areuhat"] = {id=939,recastId=939,command="/ma"},
    ["Semih Lafihna"] = {id=940,recastId=940,command="/ma"},
    ["Elivira"] = {id=941,recastId=941,command="/ma"},
    ["Noillurie"] = {id=942,recastId=942,command="/ma"},
    ["Lhu Mhakaracca"] = {id=943,recastId=943,command="/ma"},
    ["Ferreous Coffin"] = {id=944,recastId=944,command="/ma"},
    ["Lilisette"] = {id=945,recastId=945,command="/ma"},
    ["Mumor"] = {id=946,recastId=946,command="/ma"},
    ["Uka Totlihn"] = {id=947,recastId=947,command="/ma"},
    ["Klara"] = {id=948,recastId=948,command="/ma"},
    ["Romaa Mihgo"] = {id=949,recastId=949,command="/ma"},
    ["Kuyin Hathdenna"] = {id=950,recastId=950,command="/ma"},
    ["Rahal"] = {id=951,recastId=951,command="/ma"},
    ["Koru-Moru"] = {id=952,recastId=952,command="/ma"},
    ["Pieuje (UC)"] = {id=953,recastId=953,command="/ma"},
    ["I. Shield (UC)"] = {id=954,recastId=954,command="/ma"},
    ["Apururu (UC)"] = {id=955,recastId=955,command="/ma"},
    ["Jakoh (UC)"] = {id=956,recastId=956,command="/ma"},
    ["Flaviria (UC)"] = {id=957,recastId=957,command="/ma"},
    ["Babban"] = {id=958,recastId=958,command="/ma"},
    ["Abenzio"] = {id=959,recastId=959,command="/ma"},
    ["Rughadjeen"] = {id=960,recastId=960,command="/ma"},
    ["Kukki-Chebukki"] = {id=961,recastId=961,command="/ma"},
    ["Margret"] = {id=962,recastId=962,command="/ma"},
    ["Chacharoon"] = {id=963,recastId=963,command="/ma"},
    ["Lhe Lhangavo"] = {id=964,recastId=964,command="/ma"},
    ["Arciela"] = {id=965,recastId=965,command="/ma"},
    ["Mayakov"] = {id=966,recastId=966,command="/ma"},
    ["Qultada"] = {id=967,recastId=967,command="/ma"},
    ["Adelheid"] = {id=968,recastId=968,command="/ma"},
    ["Amchuchu"] = {id=969,recastId=969,command="/ma"},
    ["Brygid"] = {id=970,recastId=970,command="/ma"},
    ["Mildaurion"] = {id=971,recastId=971,command="/ma"},
    ["Halver"] = {id=972,recastId=972,command="/ma"},
    ["Rongelouts"] = {id=973,recastId=973,command="/ma"},
    ["Leonoyne"] = {id=974,recastId=974,command="/ma"},
    ["Maximilian"] = {id=975,recastId=975,command="/ma"},
    ["Kayeel-Payeel"] = {id=976,recastId=976,command="/ma"},
    ["Robel-Akbel"] = {id=977,recastId=977,command="/ma"},
    ["Kupofried"] = {id=978,recastId=978,command="/ma"},
    ["Selh'teus"] = {id=979,recastId=979,command="/ma"},
    ["Yoran-Oran (UC)"] = {id=980,recastId=980,command="/ma"},
    ["Sylvie (UC)"] = {id=981,recastId=981,command="/ma"},
    ["Abquhbah"] = {id=982,recastId=982,command="/ma"},
    ["Balamor"] = {id=983,recastId=983,command="/ma"},
    ["August"] = {id=984,recastId=984,command="/ma"},
    ["Rosulatia"] = {id=985,recastId=985,command="/ma"},
    ["Teodor"] = {id=986,recastId=986,command="/ma"},
    ["Ullegore"] = {id=987,recastId=987,command="/ma"},
    ["Makki-Chebukki"] = {id=988,recastId=988,command="/ma"},
    ["King of Hearts"] = {id=989,recastId=989,command="/ma"},
    ["Morimar"] = {id=990,recastId=990,command="/ma"},
    ["Darrcuiln"] = {id=991,recastId=991,command="/ma"},
    ["AAHM"] = {id=992,recastId=992,command="/ma"},
    ["AAEV"] = {id=993,recastId=993,command="/ma"},
    ["AAMR"] = {id=994,recastId=994,command="/ma"},
    ["AATT"] = {id=995,recastId=995,command="/ma"},
    ["AAGK"] = {id=996,recastId=996,command="/ma"},
    ["Iroha"] = {id=997,recastId=997,command="/ma"},
    ["Ygnas"] = {id=998,recastId=998,command="/ma"},
    ["Monberaux"] = {id=999,recastId=999,command="/ma"},
    ["Excenmille [S]"] = {id=1004,recastId=1004,command="/ma"},
    ["Ayame (UC)"] = {id=1005,recastId=1005,command="/ma"},
    ["Maat (UC)"] = {id=1006,recastId=1006,command="/ma"},
    ["Aldo (UC)"] = {id=1007,recastId=1007,command="/ma"},
    ["Naja (UC)"] = {id=1008,recastId=1008,command="/ma"},
    ["Lion II"] = {id=1009,recastId=1009,command="/ma"},
    ["Zeid II"] = {id=1010,recastId=1010,command="/ma"},
    ["Prishe II"] = {id=1011,recastId=1011,command="/ma"},
    ["Nashmeira II"] = {id=1012,recastId=1012,command="/ma"},
    ["Lilisette II"] = {id=1013,recastId=1013,command="/ma"},
    ["Tenzen II"] = {id=1014,recastId=1014,command="/ma"},
    ["Mumor II"] = {id=1015,recastId=1015,command="/ma"},
    ["Ingrid II"] = {id=1016,recastId=1016,command="/ma"},
    ["Arciela II"] = {id=1017,recastId=1017,command="/ma"},
    ["Iroha II"] = {id=1018,recastId=1018,command="/ma"},
    ["Shantotto II"] = {id=1019,recastId=1019,command="/ma"},
}